export const DEGODSMAPPER = {
  Backgrounds: {
    Alaska: {
      '1': 'Backgrounds/Alaska/1.png',
      '2': 'Backgrounds/Alaska/2.png',
      '3': 'Backgrounds/Alaska/3.png',
      '4': 'Backgrounds/Alaska/4.png',
    },
    Blue: {
      '1': 'Backgrounds/Blue/1.png',
      '2': 'Backgrounds/Blue/2.png',
      '3': 'Backgrounds/Blue/3.png',
      '4': 'Backgrounds/Blue/4.png',
    },
    Brown: {
      '1': 'Backgrounds/Brown/1.png',
      '2': 'Backgrounds/Brown/2.png',
      '3': 'Backgrounds/Brown/3.png',
      '4': 'Backgrounds/Brown/4.png',
    },
    Deep_Ocean_Blue: {
      '1': 'Backgrounds/Deep_Ocean_Blue/1.png',
      '2': 'Backgrounds/Deep_Ocean_Blue/2.png',
      '3': 'Backgrounds/Deep_Ocean_Blue/3.png',
      '.DS_Store': 'Backgrounds/Deep_Ocean_Blue/.DS_Store',
      deep_ocean_blue: 'Backgrounds/Deep_Ocean_Blue/deep_ocean_blue.png',
    },
    Heaven: {
      '1': 'Backgrounds/Heaven/1.png',
      '2': 'Backgrounds/Heaven/2.png',
      '3': 'Backgrounds/Heaven/3.png',
      '4': 'Backgrounds/Heaven/4.png',
      '5': 'Backgrounds/Heaven/5.png',
      '6': 'Backgrounds/Heaven/6.png',
    },
    Hell: {
      '1': 'Backgrounds/Hell/1.png',
      '2': 'Backgrounds/Hell/2.png',
      '3': 'Backgrounds/Hell/3.png',
      '4': 'Backgrounds/Hell/4.png',
      '5': 'Backgrounds/Hell/5.png',
      '6': 'Backgrounds/Hell/6.png',
      '7': 'Backgrounds/Hell/7.png',
    },
    Olive_Green: {
      '1': 'Backgrounds/Olive_Green/1.png',
      '2': 'Backgrounds/Olive_Green/2.png',
      '3': 'Backgrounds/Olive_Green/3.png',
      '.DS_Store': 'Backgrounds/Olive_Green/.DS_Store',
      olive_green: 'Backgrounds/Olive_Green/olive_green.png',
    },
    Purple: {
      '1': 'Backgrounds/Purple/1.png',
      '2': 'Backgrounds/Purple/2.png',
      '3': 'Backgrounds/Purple/3.png',
    },
    Red: {
      '1': 'Backgrounds/Red/1.png',
      '2': 'Backgrounds/Red/2.png',
      '3': 'Backgrounds/Red/3.png',
    },
    Supernova: {
      '1': 'Backgrounds/Supernova/1.png',
      '2': 'Backgrounds/Supernova/2.png',
      '3': 'Backgrounds/Supernova/3.png',
      '4': 'Backgrounds/Supernova/4.png',
      '5': 'Backgrounds/Supernova/5.png',
      '6': 'Backgrounds/Supernova/6.png',
      '7': 'Backgrounds/Supernova/7.png',
    },
    Teal: {
      Teal: 'Backgrounds/Teal/Teal.png',
    },
  },
  Clothes: {
    Bleached_Tee: {
      '.DS_Store': 'Clothes/Bleached_Tee/.DS_Store',
      'Bleached_Tee 1': 'Clothes/Bleached_Tee/Bleached_Tee 1.png',
      'Bleached_Tee 2': 'Clothes/Bleached_Tee/Bleached_Tee 2.png',
      'Bleached_Tee 3': 'Clothes/Bleached_Tee/Bleached_Tee 3.png',
      'Bleached_Tee 4': 'Clothes/Bleached_Tee/Bleached_Tee 4.png',
      'Bleached_Tee 5': 'Clothes/Bleached_Tee/Bleached_Tee 5.png',
      'Bleached_Tee 6': 'Clothes/Bleached_Tee/Bleached_Tee 6.png',
      'Bleached_Tee 7': 'Clothes/Bleached_Tee/Bleached_Tee 7.png',
    },
    Bloody_Beater: {
      '.DS_Store': 'Clothes/Bloody_Beater/.DS_Store',
      'Bloody_Beater 1': 'Clothes/Bloody_Beater/Bloody_Beater 1.png',
      'Bloody_Beater 2': 'Clothes/Bloody_Beater/Bloody_Beater 2.png',
      'Bloody_Beater 3': 'Clothes/Bloody_Beater/Bloody_Beater 3.png',
      'Bloody_Beater 4': 'Clothes/Bloody_Beater/Bloody_Beater 4.png',
      'Bloody_Beater 5': 'Clothes/Bloody_Beater/Bloody_Beater 5.png',
      'Bloody_Beater 6': 'Clothes/Bloody_Beater/Bloody_Beater 6.png',
    },
    Caesar_Tunic: {
      '.DS_Store': 'Clothes/Caesar_Tunic/.DS_Store',
      'Caesar_Tunic 1': 'Clothes/Caesar_Tunic/Caesar_Tunic 1.png',
      'Caesar_Tunic 2': 'Clothes/Caesar_Tunic/Caesar_Tunic 2.png',
      'Caesar_Tunic 3': 'Clothes/Caesar_Tunic/Caesar_Tunic 3.png',
      'Caesar_Tunic 4': 'Clothes/Caesar_Tunic/Caesar_Tunic 4.png',
      'Caesar_Tunic 5': 'Clothes/Caesar_Tunic/Caesar_Tunic 5.png',
      'Caesar_Tunic 6': 'Clothes/Caesar_Tunic/Caesar_Tunic 6.png',
      'Caesar_Tunic 7': 'Clothes/Caesar_Tunic/Caesar_Tunic 7.png',
    },
    DeDoctor_Coat: {
      '.DS_Store': 'Clothes/DeDoctor_Coat/.DS_Store',
      'DeDoctor_Coat 1': 'Clothes/DeDoctor_Coat/DeDoctor_Coat 1.png',
      'DeDoctor_Coat 2': 'Clothes/DeDoctor_Coat/DeDoctor_Coat 2.png',
      'DeDoctor_Coat 3': 'Clothes/DeDoctor_Coat/DeDoctor_Coat 3.png',
      'DeDoctor_Coat 4': 'Clothes/DeDoctor_Coat/DeDoctor_Coat 4.png',
      'DeDoctor_Coat 5': 'Clothes/DeDoctor_Coat/DeDoctor_Coat 5.png',
      'DeDoctor_Coat 6': 'Clothes/DeDoctor_Coat/DeDoctor_Coat 6.png',
    },
    DeGod_Cutoff: {
      '.DS_Store': 'Clothes/DeGod_Cutoff/.DS_Store',
      'DeGod_Cutoff 1': 'Clothes/DeGod_Cutoff/DeGod_Cutoff 1.png',
      'DeGod_Cutoff 2': 'Clothes/DeGod_Cutoff/DeGod_Cutoff 2.png',
      'DeGod_Cutoff 3': 'Clothes/DeGod_Cutoff/DeGod_Cutoff 3.png',
      'DeGod_Cutoff 4': 'Clothes/DeGod_Cutoff/DeGod_Cutoff 4.png',
      'DeGod_Cutoff 5': 'Clothes/DeGod_Cutoff/DeGod_Cutoff 5.png',
      'DeGod_Cutoff 6': 'Clothes/DeGod_Cutoff/DeGod_Cutoff 6.png',
      'DeGod_Cutoff 7': 'Clothes/DeGod_Cutoff/DeGod_Cutoff 7.png',
      'DeGod_Cutoff 8': 'Clothes/DeGod_Cutoff/DeGod_Cutoff 8.png',
      'DeGod_Cutoff 9': 'Clothes/DeGod_Cutoff/DeGod_Cutoff 9.png',
    },
    Divine_Robe: {
      '.DS_Store': 'Clothes/Divine_Robe/.DS_Store',
      'Divine_Robe 1': 'Clothes/Divine_Robe/Divine_Robe 1.png',
      'Divine_Robe 10': 'Clothes/Divine_Robe/Divine_Robe 10.png',
      'Divine_Robe 11': 'Clothes/Divine_Robe/Divine_Robe 11.png',
      'Divine_Robe 12': 'Clothes/Divine_Robe/Divine_Robe 12.png',
      'Divine_Robe 13': 'Clothes/Divine_Robe/Divine_Robe 13.png',
      'Divine_Robe 14': 'Clothes/Divine_Robe/Divine_Robe 14.png',
      'Divine_Robe 2': 'Clothes/Divine_Robe/Divine_Robe 2.png',
      'Divine_Robe 3': 'Clothes/Divine_Robe/Divine_Robe 3.png',
      'Divine_Robe 4': 'Clothes/Divine_Robe/Divine_Robe 4.png',
      'Divine_Robe 5': 'Clothes/Divine_Robe/Divine_Robe 5.png',
      'Divine_Robe 6': 'Clothes/Divine_Robe/Divine_Robe 6.png',
      'Divine_Robe 7': 'Clothes/Divine_Robe/Divine_Robe 7.png',
      'Divine_Robe 8': 'Clothes/Divine_Robe/Divine_Robe 8.png',
      'Divine_Robe 9': 'Clothes/Divine_Robe/Divine_Robe 9.png',
    },
    Druglord_Suit: {
      '.DS_Store': 'Clothes/Druglord_Suit/.DS_Store',
      'Druglord_Suit 1': 'Clothes/Druglord_Suit/Druglord_Suit 1.png',
      'Druglord_Suit 10': 'Clothes/Druglord_Suit/Druglord_Suit 10.png',
      'Druglord_Suit 11': 'Clothes/Druglord_Suit/Druglord_Suit 11.png',
      'Druglord_Suit 2': 'Clothes/Druglord_Suit/Druglord_Suit 2.png',
      'Druglord_Suit 3': 'Clothes/Druglord_Suit/Druglord_Suit 3.png',
      'Druglord_Suit 4': 'Clothes/Druglord_Suit/Druglord_Suit 4.png',
      'Druglord_Suit 5': 'Clothes/Druglord_Suit/Druglord_Suit 5.png',
      'Druglord_Suit 6': 'Clothes/Druglord_Suit/Druglord_Suit 6.png',
      'Druglord_Suit 7': 'Clothes/Druglord_Suit/Druglord_Suit 7.png',
      'Druglord_Suit 8': 'Clothes/Druglord_Suit/Druglord_Suit 8.png',
      'Druglord_Suit 9': 'Clothes/Druglord_Suit/Druglord_Suit 9.png',
    },
    FTX_Jersey: {
      '.DS_Store': 'Clothes/FTX_Jersey/.DS_Store',
      'FTX_Jersey 1': 'Clothes/FTX_Jersey/FTX_Jersey 1.png',
      'FTX_Jersey 2': 'Clothes/FTX_Jersey/FTX_Jersey 2.png',
      'FTX_Jersey 3': 'Clothes/FTX_Jersey/FTX_Jersey 3.png',
      'FTX_Jersey 4': 'Clothes/FTX_Jersey/FTX_Jersey 4.png',
      'FTX_Jersey 5': 'Clothes/FTX_Jersey/FTX_Jersey 5.png',
      'FTX_Jersey 6': 'Clothes/FTX_Jersey/FTX_Jersey 6.png',
      'FTX_Jersey 7': 'Clothes/FTX_Jersey/FTX_Jersey 7.png',
    },
    God_Beater: {
      '.DS_Store': 'Clothes/God_Beater/.DS_Store',
      'God_Beater 1': 'Clothes/God_Beater/God_Beater 1.png',
      'God_Beater 2': 'Clothes/God_Beater/God_Beater 2.png',
      'God_Beater 3': 'Clothes/God_Beater/God_Beater 3.png',
      'God_Beater 4': 'Clothes/God_Beater/God_Beater 4.png',
      'God_Beater 5': 'Clothes/God_Beater/God_Beater 5.png',
    },
    God_Jersey: {
      '.DS_Store': 'Clothes/God_Jersey/.DS_Store',
      'God_Jersey 1': 'Clothes/God_Jersey/God_Jersey 1.png',
      'God_Jersey 2': 'Clothes/God_Jersey/God_Jersey 2.png',
      'God_Jersey 3': 'Clothes/God_Jersey/God_Jersey 3.png',
      'God_Jersey 4': 'Clothes/God_Jersey/God_Jersey 4.png',
      'God_Jersey 5': 'Clothes/God_Jersey/God_Jersey 5.png',
    },
    God_Scout_Uniform: {
      '.DS_Store': 'Clothes/God_Scout_Uniform/.DS_Store',
      'God_Scout_Uniform 1':
        'Clothes/God_Scout_Uniform/God_Scout_Uniform 1.png',
      'God_Scout_Uniform 10':
        'Clothes/God_Scout_Uniform/God_Scout_Uniform 10.png',
      'God_Scout_Uniform 11':
        'Clothes/God_Scout_Uniform/God_Scout_Uniform 11.png',
      'God_Scout_Uniform 2':
        'Clothes/God_Scout_Uniform/God_Scout_Uniform 2.png',
      'God_Scout_Uniform 3':
        'Clothes/God_Scout_Uniform/God_Scout_Uniform 3.png',
      'God_Scout_Uniform 4':
        'Clothes/God_Scout_Uniform/God_Scout_Uniform 4.png',
      'God_Scout_Uniform 5':
        'Clothes/God_Scout_Uniform/God_Scout_Uniform 5.png',
      'God_Scout_Uniform 6':
        'Clothes/God_Scout_Uniform/God_Scout_Uniform 6.png',
      'God_Scout_Uniform 7':
        'Clothes/God_Scout_Uniform/God_Scout_Uniform 7.png',
      'God_Scout_Uniform 8':
        'Clothes/God_Scout_Uniform/God_Scout_Uniform 8.png',
      'God_Scout_Uniform 9':
        'Clothes/God_Scout_Uniform/God_Scout_Uniform 9.png',
    },
    Godchella_Hoodie: {
      '.DS_Store': 'Clothes/Godchella_Hoodie/.DS_Store',
      'Godchella_Hoodie 1': 'Clothes/Godchella_Hoodie/Godchella_Hoodie 1.png',
      'Godchella_Hoodie 10': 'Clothes/Godchella_Hoodie/Godchella_Hoodie 10.png',
      'Godchella_Hoodie 2': 'Clothes/Godchella_Hoodie/Godchella_Hoodie 2.png',
      'Godchella_Hoodie 3': 'Clothes/Godchella_Hoodie/Godchella_Hoodie 3.png',
      'Godchella_Hoodie 4': 'Clothes/Godchella_Hoodie/Godchella_Hoodie 4.png',
      'Godchella_Hoodie 5': 'Clothes/Godchella_Hoodie/Godchella_Hoodie 5.png',
      'Godchella_Hoodie 6': 'Clothes/Godchella_Hoodie/Godchella_Hoodie 6.png',
      'Godchella_Hoodie 7': 'Clothes/Godchella_Hoodie/Godchella_Hoodie 7.png',
      'Godchella_Hoodie 8': 'Clothes/Godchella_Hoodie/Godchella_Hoodie 8.png',
      'Godchella_Hoodie 9': 'Clothes/Godchella_Hoodie/Godchella_Hoodie 9.png',
    },
    Godly_Tunic: {
      '.DS_Store': 'Clothes/Godly_Tunic/.DS_Store',
      'Godly_Tunic 1': 'Clothes/Godly_Tunic/Godly_Tunic 1.png',
      'Godly_Tunic 2': 'Clothes/Godly_Tunic/Godly_Tunic 2.png',
      'Godly_Tunic 3': 'Clothes/Godly_Tunic/Godly_Tunic 3.png',
      'Godly_Tunic 4': 'Clothes/Godly_Tunic/Godly_Tunic 4.png',
      'Godly_Tunic 5': 'Clothes/Godly_Tunic/Godly_Tunic 5.png',
      'Godly_Tunic 6': 'Clothes/Godly_Tunic/Godly_Tunic 6.png',
      'Godly_Tunic 7': 'Clothes/Godly_Tunic/Godly_Tunic 7.png',
    },
    Googod_Tee: {
      '.DS_Store': 'Clothes/Googod_Tee/.DS_Store',
      'Googod_Tee 1': 'Clothes/Googod_Tee/Googod_Tee 1.png',
      'Googod_Tee 2': 'Clothes/Googod_Tee/Googod_Tee 2.png',
      'Googod_Tee 3': 'Clothes/Googod_Tee/Googod_Tee 3.png',
      'Googod_Tee 4': 'Clothes/Googod_Tee/Googod_Tee 4.png',
      'Googod_Tee 5': 'Clothes/Googod_Tee/Googod_Tee 5.png',
      'Googod_Tee 6': 'Clothes/Googod_Tee/Googod_Tee 6.png',
    },
    Gym_Tee: {
      '.DS_Store': 'Clothes/Gym_Tee/.DS_Store',
      'Gym_Tee 1': 'Clothes/Gym_Tee/Gym_Tee 1.png',
      'Gym_Tee 2': 'Clothes/Gym_Tee/Gym_Tee 2.png',
      'Gym_Tee 3': 'Clothes/Gym_Tee/Gym_Tee 3.png',
      'Gym_Tee 4': 'Clothes/Gym_Tee/Gym_Tee 4.png',
      'Gym_Tee 5': 'Clothes/Gym_Tee/Gym_Tee 5.png',
      'Gym_Tee 6': 'Clothes/Gym_Tee/Gym_Tee 6.png',
      'Gym_Tee 7': 'Clothes/Gym_Tee/Gym_Tee 7.png',
      'Gym_Tee 8': 'Clothes/Gym_Tee/Gym_Tee 8.png',
      'Gym_Tee 9': 'Clothes/Gym_Tee/Gym_Tee 9.png',
    },
    Hawaiian_Shirt: {
      '.DS_Store': 'Clothes/Hawaiian_Shirt/.DS_Store',
      'Hawaiian_Shirt 1': 'Clothes/Hawaiian_Shirt/Hawaiian_Shirt 1.png',
      'Hawaiian_Shirt 2': 'Clothes/Hawaiian_Shirt/Hawaiian_Shirt 2.png',
      'Hawaiian_Shirt 3': 'Clothes/Hawaiian_Shirt/Hawaiian_Shirt 3.png',
      'Hawaiian_Shirt 4': 'Clothes/Hawaiian_Shirt/Hawaiian_Shirt 4.png',
      'Hawaiian_Shirt 5': 'Clothes/Hawaiian_Shirt/Hawaiian_Shirt 5.png',
      'Hawaiian_Shirt 6': 'Clothes/Hawaiian_Shirt/Hawaiian_Shirt 6.png',
      'Hawaiian_Shirt 7': 'Clothes/Hawaiian_Shirt/Hawaiian_Shirt 7.png',
    },
    Hazmat_Suit: {
      '1': 'Clothes/Hazmat_Suit/1.png',
      '2': 'Clothes/Hazmat_Suit/2.png',
      '3': 'Clothes/Hazmat_Suit/3.png',
      '4': 'Clothes/Hazmat_Suit/4.png',
      '5': 'Clothes/Hazmat_Suit/5.png',
      '6': 'Clothes/Hazmat_Suit/6.png',
      '7': 'Clothes/Hazmat_Suit/7.png',
      '8': 'Clothes/Hazmat_Suit/8.png',
      '9': 'Clothes/Hazmat_Suit/9.png',
    },
    Jean_Jacket: {
      '.DS_Store': 'Clothes/Jean_Jacket/.DS_Store',
      'Jean_Jacket 1': 'Clothes/Jean_Jacket/Jean_Jacket 1.png',
      'Jean_Jacket 2': 'Clothes/Jean_Jacket/Jean_Jacket 2.png',
      'Jean_Jacket 3': 'Clothes/Jean_Jacket/Jean_Jacket 3.png',
      'Jean_Jacket 4': 'Clothes/Jean_Jacket/Jean_Jacket 4.png',
      'Jean_Jacket 5': 'Clothes/Jean_Jacket/Jean_Jacket 5.png',
      'Jean_Jacket 6': 'Clothes/Jean_Jacket/Jean_Jacket 6.png',
      'Jean_Jacket 7': 'Clothes/Jean_Jacket/Jean_Jacket 7.png',
      'Jean_Jacket 8': 'Clothes/Jean_Jacket/Jean_Jacket 8.png',
      'Jean_Jacket 9': 'Clothes/Jean_Jacket/Jean_Jacket 9.png',
    },
    Mickey_DeGods_Uniform: {
      '.DS_Store': 'Clothes/Mickey_DeGods_Uniform/.DS_Store',
      'Mickey_DeGods_Uniform 1':
        'Clothes/Mickey_DeGods_Uniform/Mickey_DeGods_Uniform 1.png',
      'Mickey_DeGods_Uniform 2':
        'Clothes/Mickey_DeGods_Uniform/Mickey_DeGods_Uniform 2.png',
      'Mickey_DeGods_Uniform 3':
        'Clothes/Mickey_DeGods_Uniform/Mickey_DeGods_Uniform 3.png',
      'Mickey_DeGods_Uniform 4':
        'Clothes/Mickey_DeGods_Uniform/Mickey_DeGods_Uniform 4.png',
      'Mickey_DeGods_Uniform 5':
        'Clothes/Mickey_DeGods_Uniform/Mickey_DeGods_Uniform 5.png',
      'Mickey_DeGods_Uniform 6':
        'Clothes/Mickey_DeGods_Uniform/Mickey_DeGods_Uniform 6.png',
      'Mickey_DeGods_Uniform 7':
        'Clothes/Mickey_DeGods_Uniform/Mickey_DeGods_Uniform 7.png',
      'Mickey_DeGods_Uniform 8':
        'Clothes/Mickey_DeGods_Uniform/Mickey_DeGods_Uniform 8.png',
      'Mickey_DeGods_Uniform 9':
        'Clothes/Mickey_DeGods_Uniform/Mickey_DeGods_Uniform 9.png',
    },
    Mythic_War_Armor: {
      '.DS_Store': 'Clothes/Mythic_War_Armor/.DS_Store',
      'Mythic_War_Armor 1': 'Clothes/Mythic_War_Armor/Mythic_War_Armor 1.png',
      'Mythic_War_Armor 10': 'Clothes/Mythic_War_Armor/Mythic_War_Armor 10.png',
      'Mythic_War_Armor 11': 'Clothes/Mythic_War_Armor/Mythic_War_Armor 11.png',
      'Mythic_War_Armor 12': 'Clothes/Mythic_War_Armor/Mythic_War_Armor 12.png',
      'Mythic_War_Armor 13': 'Clothes/Mythic_War_Armor/Mythic_War_Armor 13.png',
      'Mythic_War_Armor 14': 'Clothes/Mythic_War_Armor/Mythic_War_Armor 14.png',
      'Mythic_War_Armor 2': 'Clothes/Mythic_War_Armor/Mythic_War_Armor 2.png',
      'Mythic_War_Armor 3': 'Clothes/Mythic_War_Armor/Mythic_War_Armor 3.png',
      'Mythic_War_Armor 4': 'Clothes/Mythic_War_Armor/Mythic_War_Armor 4.png',
      'Mythic_War_Armor 5': 'Clothes/Mythic_War_Armor/Mythic_War_Armor 5.png',
      'Mythic_War_Armor 6': 'Clothes/Mythic_War_Armor/Mythic_War_Armor 6.png',
      'Mythic_War_Armor 7': 'Clothes/Mythic_War_Armor/Mythic_War_Armor 7.png',
      'Mythic_War_Armor 8': 'Clothes/Mythic_War_Armor/Mythic_War_Armor 8.png',
      'Mythic_War_Armor 9': 'Clothes/Mythic_War_Armor/Mythic_War_Armor 9.png',
    },
    Overalls: {
      '.DS_Store': 'Clothes/Overalls/.DS_Store',
      'Overalls 1': 'Clothes/Overalls/Overalls 1.png',
      'Overalls 2': 'Clothes/Overalls/Overalls 2.png',
      'Overalls 3': 'Clothes/Overalls/Overalls 3.png',
      'Overalls 4': 'Clothes/Overalls/Overalls 4.png',
      'Overalls 5': 'Clothes/Overalls/Overalls 5.png',
      'Overalls 6': 'Clothes/Overalls/Overalls 6.png',
      'Overalls 7': 'Clothes/Overalls/Overalls 7.png',
      'Overalls 8': 'Clothes/Overalls/Overalls 8.png',
    },
    Peasant_Blouse: {
      '.DS_Store': 'Clothes/Peasant_Blouse/.DS_Store',
      'Peasant_Blouse 1': 'Clothes/Peasant_Blouse/Peasant_Blouse 1.png',
      'Peasant_Blouse 2': 'Clothes/Peasant_Blouse/Peasant_Blouse 2.png',
      'Peasant_Blouse 3': 'Clothes/Peasant_Blouse/Peasant_Blouse 3.png',
      'Peasant_Blouse 4': 'Clothes/Peasant_Blouse/Peasant_Blouse 4.png',
      'Peasant_Blouse 5': 'Clothes/Peasant_Blouse/Peasant_Blouse 5.png',
      'Peasant_Blouse 6': 'Clothes/Peasant_Blouse/Peasant_Blouse 6.png',
      'Peasant_Blouse 7': 'Clothes/Peasant_Blouse/Peasant_Blouse 7.png',
    },
    Radioactive_Tee: {
      '.DS_Store': 'Clothes/Radioactive_Tee/.DS_Store',
      'Radioactive_Tee 1': 'Clothes/Radioactive_Tee/Radioactive_Tee 1.png',
      'Radioactive_Tee 2': 'Clothes/Radioactive_Tee/Radioactive_Tee 2.png',
      'Radioactive_Tee 3': 'Clothes/Radioactive_Tee/Radioactive_Tee 3.png',
      'Radioactive_Tee 4': 'Clothes/Radioactive_Tee/Radioactive_Tee 4.png',
      'Radioactive_Tee 5': 'Clothes/Radioactive_Tee/Radioactive_Tee 5.png',
      'Radioactive_Tee 6': 'Clothes/Radioactive_Tee/Radioactive_Tee 6.png',
      'Radioactive_Tee 7': 'Clothes/Radioactive_Tee/Radioactive_Tee 7.png',
    },
    Silk_Robe: {
      '.DS_Store': 'Clothes/Silk_Robe/.DS_Store',
      'Silk_Robe 1': 'Clothes/Silk_Robe/Silk_Robe 1.png',
      'Silk_Robe 10': 'Clothes/Silk_Robe/Silk_Robe 10.png',
      'Silk_Robe 2': 'Clothes/Silk_Robe/Silk_Robe 2.png',
      'Silk_Robe 3': 'Clothes/Silk_Robe/Silk_Robe 3.png',
      'Silk_Robe 4': 'Clothes/Silk_Robe/Silk_Robe 4.png',
      'Silk_Robe 5': 'Clothes/Silk_Robe/Silk_Robe 5.png',
      'Silk_Robe 6': 'Clothes/Silk_Robe/Silk_Robe 6.png',
      'Silk_Robe 7': 'Clothes/Silk_Robe/Silk_Robe 7.png',
      'Silk_Robe 8': 'Clothes/Silk_Robe/Silk_Robe 8.png',
      'Silk_Robe 9': 'Clothes/Silk_Robe/Silk_Robe 9.png',
    },
    Steve_Jobs_Turtleneck: {
      '.DS_Store': 'Clothes/Steve_Jobs_Turtleneck/.DS_Store',
      'Steve_Jobs_Turtleneck 1':
        'Clothes/Steve_Jobs_Turtleneck/Steve_Jobs_Turtleneck 1.png',
      'Steve_Jobs_Turtleneck 2':
        'Clothes/Steve_Jobs_Turtleneck/Steve_Jobs_Turtleneck 2.png',
      'Steve_Jobs_Turtleneck 3':
        'Clothes/Steve_Jobs_Turtleneck/Steve_Jobs_Turtleneck 3.png',
      'Steve_Jobs_Turtleneck 4':
        'Clothes/Steve_Jobs_Turtleneck/Steve_Jobs_Turtleneck 4.png',
      'Steve_Jobs_Turtleneck 5':
        'Clothes/Steve_Jobs_Turtleneck/Steve_Jobs_Turtleneck 5.png',
      'Steve_Jobs_Turtleneck 6':
        'Clothes/Steve_Jobs_Turtleneck/Steve_Jobs_Turtleneck 6.png',
      'Steve_Jobs_Turtleneck 7':
        'Clothes/Steve_Jobs_Turtleneck/Steve_Jobs_Turtleneck 7.png',
    },
    Tattered_Tee: {
      '.DS_Store': 'Clothes/Tattered_Tee/.DS_Store',
      'Tattered_Tee 1': 'Clothes/Tattered_Tee/Tattered_Tee 1.png',
      'Tattered_Tee 2': 'Clothes/Tattered_Tee/Tattered_Tee 2.png',
      'Tattered_Tee 3': 'Clothes/Tattered_Tee/Tattered_Tee 3.png',
      'Tattered_Tee 4': 'Clothes/Tattered_Tee/Tattered_Tee 4.png',
      'Tattered_Tee 5': 'Clothes/Tattered_Tee/Tattered_Tee 5.png',
      'Tattered_Tee 6': 'Clothes/Tattered_Tee/Tattered_Tee 6.png',
      'Tattered_Tee 7': 'Clothes/Tattered_Tee/Tattered_Tee 7.png',
    },
    Tech_God_Vest: {
      '.DS_Store': 'Clothes/Tech_God_Vest/.DS_Store',
      'Tech_God_Vest 1': 'Clothes/Tech_God_Vest/Tech_God_Vest 1.png',
      'Tech_God_Vest 2': 'Clothes/Tech_God_Vest/Tech_God_Vest 2.png',
      'Tech_God_Vest 3': 'Clothes/Tech_God_Vest/Tech_God_Vest 3.png',
      'Tech_God_Vest 4': 'Clothes/Tech_God_Vest/Tech_God_Vest 4.png',
      'Tech_God_Vest 5': 'Clothes/Tech_God_Vest/Tech_God_Vest 5.png',
      'Tech_God_Vest 6': 'Clothes/Tech_God_Vest/Tech_God_Vest 6.png',
      'Tech_God_Vest 7': 'Clothes/Tech_God_Vest/Tech_God_Vest 7.png',
      'Tech_God_Vest 8': 'Clothes/Tech_God_Vest/Tech_God_Vest 8.png',
      'Tech_God_Vest 9': 'Clothes/Tech_God_Vest/Tech_God_Vest 9.png',
    },
    Top_God_Jumper: {
      '.DS_Store': 'Clothes/Top_God_Jumper/.DS_Store',
      'Top_God_Jumper 1': 'Clothes/Top_God_Jumper/Top_God_Jumper 1.png',
      'Top_God_Jumper 10': 'Clothes/Top_God_Jumper/Top_God_Jumper 10.png',
      'Top_God_Jumper 2': 'Clothes/Top_God_Jumper/Top_God_Jumper 2.png',
      'Top_God_Jumper 3': 'Clothes/Top_God_Jumper/Top_God_Jumper 3.png',
      'Top_God_Jumper 4': 'Clothes/Top_God_Jumper/Top_God_Jumper 4.png',
      'Top_God_Jumper 5': 'Clothes/Top_God_Jumper/Top_God_Jumper 5.png',
      'Top_God_Jumper 6': 'Clothes/Top_God_Jumper/Top_God_Jumper 6.png',
      'Top_God_Jumper 7': 'Clothes/Top_God_Jumper/Top_God_Jumper 7.png',
      'Top_God_Jumper 8': 'Clothes/Top_God_Jumper/Top_God_Jumper 8.png',
      'Top_God_Jumper 9': 'Clothes/Top_God_Jumper/Top_God_Jumper 9.png',
    },
    Tourist_Tee: {
      '.DS_Store': 'Clothes/Tourist_Tee/.DS_Store',
      'Tourist_Tee 1': 'Clothes/Tourist_Tee/Tourist_Tee 1.png',
      'Tourist_Tee 2': 'Clothes/Tourist_Tee/Tourist_Tee 2.png',
      'Tourist_Tee 3': 'Clothes/Tourist_Tee/Tourist_Tee 3.png',
      'Tourist_Tee 4': 'Clothes/Tourist_Tee/Tourist_Tee 4.png',
      'Tourist_Tee 5': 'Clothes/Tourist_Tee/Tourist_Tee 5.png',
      'Tourist_Tee 6': 'Clothes/Tourist_Tee/Tourist_Tee 6.png',
      'Tourist_Tee 7': 'Clothes/Tourist_Tee/Tourist_Tee 7.png',
      'Tourist_Tee 8': 'Clothes/Tourist_Tee/Tourist_Tee 8.png',
      'Tourist_Tee 9': 'Clothes/Tourist_Tee/Tourist_Tee 9.png',
    },
    Tracksuit: {
      '.DS_Store': 'Clothes/Tracksuit/.DS_Store',
      'Tracksuit 1': 'Clothes/Tracksuit/Tracksuit 1.png',
      'Tracksuit 10': 'Clothes/Tracksuit/Tracksuit 10.png',
      'Tracksuit 11': 'Clothes/Tracksuit/Tracksuit 11.png',
      'Tracksuit 2': 'Clothes/Tracksuit/Tracksuit 2.png',
      'Tracksuit 3': 'Clothes/Tracksuit/Tracksuit 3.png',
      'Tracksuit 4': 'Clothes/Tracksuit/Tracksuit 4.png',
      'Tracksuit 5': 'Clothes/Tracksuit/Tracksuit 5.png',
      'Tracksuit 6': 'Clothes/Tracksuit/Tracksuit 6.png',
      'Tracksuit 7': 'Clothes/Tracksuit/Tracksuit 7.png',
      'Tracksuit 8': 'Clothes/Tracksuit/Tracksuit 8.png',
      'Tracksuit 9': 'Clothes/Tracksuit/Tracksuit 9.png',
    },
    War_Armor: {
      '.DS_Store': 'Clothes/War_Armor/.DS_Store',
      'War_Armor 1': 'Clothes/War_Armor/War_Armor 1.png',
      'War_Armor 10': 'Clothes/War_Armor/War_Armor 10.png',
      'War_Armor 11': 'Clothes/War_Armor/War_Armor 11.png',
      'War_Armor 12': 'Clothes/War_Armor/War_Armor 12.png',
      'War_Armor 13': 'Clothes/War_Armor/War_Armor 13.png',
      'War_Armor 14': 'Clothes/War_Armor/War_Armor 14.png',
      'War_Armor 15': 'Clothes/War_Armor/War_Armor 15.png',
      'War_Armor 2': 'Clothes/War_Armor/War_Armor 2.png',
      'War_Armor 3': 'Clothes/War_Armor/War_Armor 3.png',
      'War_Armor 4': 'Clothes/War_Armor/War_Armor 4.png',
      'War_Armor 5': 'Clothes/War_Armor/War_Armor 5.png',
      'War_Armor 6': 'Clothes/War_Armor/War_Armor 6.png',
      'War_Armor 7': 'Clothes/War_Armor/War_Armor 7.png',
      'War_Armor 8': 'Clothes/War_Armor/War_Armor 8.png',
      'War_Armor 9': 'Clothes/War_Armor/War_Armor 9.png',
    },
    World_Champion_Robe: {
      '.DS_Store': 'Clothes/World_Champion_Robe/.DS_Store',
      'World_Champion_Robe 1':
        'Clothes/World_Champion_Robe/World_Champion_Robe 1.png',
      'World_Champion_Robe 2':
        'Clothes/World_Champion_Robe/World_Champion_Robe 2.png',
      'World_Champion_Robe 3':
        'Clothes/World_Champion_Robe/World_Champion_Robe 3.png',
      'World_Champion_Robe 4':
        'Clothes/World_Champion_Robe/World_Champion_Robe 4.png',
      'World_Champion_Robe 5':
        'Clothes/World_Champion_Robe/World_Champion_Robe 5.png',
      'World_Champion_Robe 6':
        'Clothes/World_Champion_Robe/World_Champion_Robe 6.png',
      'World_Champion_Robe 7':
        'Clothes/World_Champion_Robe/World_Champion_Robe 7.png',
    },
  },
  Eyes: {
    Alien_Spectacles: {
      '1': 'Eyes/Alien_Spectacles/1.png',
      '2': 'Eyes/Alien_Spectacles/2.png',
      '3': 'Eyes/Alien_Spectacles/3.png',
      '4': 'Eyes/Alien_Spectacles/4.png',
      '5': 'Eyes/Alien_Spectacles/5.png',
      '6': 'Eyes/Alien_Spectacles/6.png',
      '7': 'Eyes/Alien_Spectacles/7.png',
      '8': 'Eyes/Alien_Spectacles/8.png',
      '9': 'Eyes/Alien_Spectacles/9.png',
    },
    All_Seeing_Eyes: {
      '1': 'Eyes/All_Seeing_Eyes/1.png',
      '2': 'Eyes/All_Seeing_Eyes/2.png',
      '3': 'Eyes/All_Seeing_Eyes/3.png',
    },
    Clout_Goggles: {
      '1': 'Eyes/Clout_Goggles/1.png',
      '2': 'Eyes/Clout_Goggles/2.png',
      '3': 'Eyes/Clout_Goggles/3.png',
      '4': 'Eyes/Clout_Goggles/4.png',
    },
    DeGucci_Goggles: {
      '1': 'Eyes/DeGucci_Goggles/1.png',
      '2': 'Eyes/DeGucci_Goggles/2.png',
      '3': 'Eyes/DeGucci_Goggles/3.png',
      '4': 'Eyes/DeGucci_Goggles/4.png',
      '5': 'Eyes/DeGucci_Goggles/5.png',
      '6': 'Eyes/DeGucci_Goggles/6.png',
      '7': 'Eyes/DeGucci_Goggles/7.png',
      '8': 'Eyes/DeGucci_Goggles/8.png',
      '9': 'Eyes/DeGucci_Goggles/9.png',
      '10': 'Eyes/DeGucci_Goggles/10.png',
      '11': 'Eyes/DeGucci_Goggles/11.png',
      '12': 'Eyes/DeGucci_Goggles/12.png',
      '13': 'Eyes/DeGucci_Goggles/13.png',
      '14': 'Eyes/DeGucci_Goggles/14.png',
    },
    DeMonacle: {
      '1': 'Eyes/DeMonacle/1.png',
      '2': 'Eyes/DeMonacle/2.png',
      '3': 'Eyes/DeMonacle/3.png',
      '4': 'Eyes/DeMonacle/4.png',
      '5': 'Eyes/DeMonacle/5.png',
      '6': 'Eyes/DeMonacle/6.png',
      '7': 'Eyes/DeMonacle/7.png',
      '8': 'Eyes/DeMonacle/8.png',
    },
    Eye_Patch: {
      '1': 'Eyes/Eye_Patch/1.png',
      '2': 'Eyes/Eye_Patch/2.png',
      '3': 'Eyes/Eye_Patch/3.png',
      '4': 'Eyes/Eye_Patch/4.png',
      '5': 'Eyes/Eye_Patch/5.png',
      '6': 'Eyes/Eye_Patch/6.png',
      '7': 'Eyes/Eye_Patch/7.png',
    },
    Glowing_Eyes: {
      '1': 'Eyes/Glowing_Eyes/1.png',
      '2': 'Eyes/Glowing_Eyes/2.png',
      '3': 'Eyes/Glowing_Eyes/3.png',
      '4': 'Eyes/Glowing_Eyes/4.png',
    },
    Laser_Eyes: {
      '1': 'Eyes/Laser_Eyes/1.png',
      '2': 'Eyes/Laser_Eyes/2.png',
      '3': 'Eyes/Laser_Eyes/3.png',
      '4': 'Eyes/Laser_Eyes/4.png',
      '5': 'Eyes/Laser_Eyes/5.png',
      '6': 'Eyes/Laser_Eyes/6.png',
      '7': 'Eyes/Laser_Eyes/7.png',
      '8': 'Eyes/Laser_Eyes/8.png',
      '9': 'Eyes/Laser_Eyes/9.png',
    },
    Money_Sign_Shades: {
      '1': 'Eyes/Money_Sign_Shades/1.png',
      '2': 'Eyes/Money_Sign_Shades/2.png',
      '3': 'Eyes/Money_Sign_Shades/3.png',
      '4': 'Eyes/Money_Sign_Shades/4.png',
      '5': 'Eyes/Money_Sign_Shades/5.png',
      '6': 'Eyes/Money_Sign_Shades/6.png',
      '7': 'Eyes/Money_Sign_Shades/7.png',
    },
    Neon_Shades: {
      '1': 'Eyes/Neon_Shades/1.png',
      '2': 'Eyes/Neon_Shades/2.png',
      '3': 'Eyes/Neon_Shades/3.png',
      '4': 'Eyes/Neon_Shades/4.png',
      '5': 'Eyes/Neon_Shades/5.png',
      '6': 'Eyes/Neon_Shades/6.png',
      '7': 'Eyes/Neon_Shades/7.png',
    },
    Night_Vision_Goggles: {
      '1': 'Eyes/Night_Vision_Goggles/1.png',
      '2': 'Eyes/Night_Vision_Goggles/2.png',
      '3': 'Eyes/Night_Vision_Goggles/3.png',
      '4': 'Eyes/Night_Vision_Goggles/4.png',
      '5': 'Eyes/Night_Vision_Goggles/5.png',
      '6': 'Eyes/Night_Vision_Goggles/6.png',
    },
    Playboy_Bunny_Glasses: {
      '1': 'Eyes/Playboy_Bunny_Glasses/1.png',
      '2': 'Eyes/Playboy_Bunny_Glasses/2.png',
      '3': 'Eyes/Playboy_Bunny_Glasses/3.png',
      '4': 'Eyes/Playboy_Bunny_Glasses/4.png',
      '5': 'Eyes/Playboy_Bunny_Glasses/5.png',
      '6': 'Eyes/Playboy_Bunny_Glasses/6.png',
      '7': 'Eyes/Playboy_Bunny_Glasses/7.png',
      '8': 'Eyes/Playboy_Bunny_Glasses/8.png',
      '9': 'Eyes/Playboy_Bunny_Glasses/9.png',
    },
    Rainbow_Laser_Eyes: {
      '1': 'Eyes/Rainbow_Laser_Eyes/1.png',
      '2': 'Eyes/Rainbow_Laser_Eyes/2.png',
      '3': 'Eyes/Rainbow_Laser_Eyes/3.png',
      '4': 'Eyes/Rainbow_Laser_Eyes/4.png',
      '5': 'Eyes/Rainbow_Laser_Eyes/5.png',
      '6': 'Eyes/Rainbow_Laser_Eyes/6.png',
      '7': 'Eyes/Rainbow_Laser_Eyes/7.png',
      '8': 'Eyes/Rainbow_Laser_Eyes/8.png',
      '9': 'Eyes/Rainbow_Laser_Eyes/9.png',
      '10': 'Eyes/Rainbow_Laser_Eyes/10.png',
    },
    Red_Wine_Glasses: {
      '1': 'Eyes/Red_Wine_Glasses/1.png',
      '2': 'Eyes/Red_Wine_Glasses/2.png',
      '3': 'Eyes/Red_Wine_Glasses/3.png',
      '4': 'Eyes/Red_Wine_Glasses/4.png',
      '5': 'Eyes/Red_Wine_Glasses/5.png',
      '6': 'Eyes/Red_Wine_Glasses/6.png',
      '7': 'Eyes/Red_Wine_Glasses/7.png',
    },
    Rose_Tinted_Shades: {
      '1': 'Eyes/Rose_Tinted_Shades/1.png',
      '2': 'Eyes/Rose_Tinted_Shades/2.png',
      '3': 'Eyes/Rose_Tinted_Shades/3.png',
      '4': 'Eyes/Rose_Tinted_Shades/4.png',
      '5': 'Eyes/Rose_Tinted_Shades/5.png',
      '6': 'Eyes/Rose_Tinted_Shades/6.png',
      '7': 'Eyes/Rose_Tinted_Shades/7.png',
      '8': 'Eyes/Rose_Tinted_Shades/8.png',
      '9': 'Eyes/Rose_Tinted_Shades/9.png',
      '10': 'Eyes/Rose_Tinted_Shades/10.png',
      '11': 'Eyes/Rose_Tinted_Shades/11.png',
      '12': 'Eyes/Rose_Tinted_Shades/12.png',
    },
    Round_Glasses: {
      '1': 'Eyes/Round_Glasses/1.png',
      '2': 'Eyes/Round_Glasses/2.png',
      '3': 'Eyes/Round_Glasses/3.png',
      '4': 'Eyes/Round_Glasses/4.png',
      '5': 'Eyes/Round_Glasses/5.png',
      '6': 'Eyes/Round_Glasses/6.png',
    },
    Rugrat_Frames: {
      '1': 'Eyes/Rugrat_Frames/1.png',
      '2': 'Eyes/Rugrat_Frames/2.png',
      '3': 'Eyes/Rugrat_Frames/3.png',
      '4': 'Eyes/Rugrat_Frames/4.png',
      '5': 'Eyes/Rugrat_Frames/5.png',
      '6': 'Eyes/Rugrat_Frames/6.png',
      '7': 'Eyes/Rugrat_Frames/7.png',
      '8': 'Eyes/Rugrat_Frames/8.png',
      '9': 'Eyes/Rugrat_Frames/9.png',
      '10': 'Eyes/Rugrat_Frames/10.png',
      '11': 'Eyes/Rugrat_Frames/11.png',
      '12': 'Eyes/Rugrat_Frames/12.png',
    },
    Snake_Eyes: {
      '1': 'Eyes/Snake_Eyes/1.png',
      '2': 'Eyes/Snake_Eyes/2.png',
      '3': 'Eyes/Snake_Eyes/3.png',
      '4': 'Eyes/Snake_Eyes/4.png',
    },
    Steampunk_Glasses: {
      '1': 'Eyes/Steampunk_Glasses/1.png',
      '2': 'Eyes/Steampunk_Glasses/2.png',
      '3': 'Eyes/Steampunk_Glasses/3.png',
      '4': 'Eyes/Steampunk_Glasses/4.png',
      '5': 'Eyes/Steampunk_Glasses/5.png',
      '6': 'Eyes/Steampunk_Glasses/6.png',
      '7': 'Eyes/Steampunk_Glasses/7.png',
      '8': 'Eyes/Steampunk_Glasses/8.png',
      '9': 'Eyes/Steampunk_Glasses/9.png',
      '10': 'Eyes/Steampunk_Glasses/10.png',
    },
    Swirly_Glasses: {
      '1': 'Eyes/Swirly_Glasses/1.png',
      '2': 'Eyes/Swirly_Glasses/2.png',
      '3': 'Eyes/Swirly_Glasses/3.png',
      '4': 'Eyes/Swirly_Glasses/4.png',
      '5': 'Eyes/Swirly_Glasses/5.png',
      '6': 'Eyes/Swirly_Glasses/6.png',
      '7': 'Eyes/Swirly_Glasses/7.png',
      '8': 'Eyes/Swirly_Glasses/8.png',
      '9': 'Eyes/Swirly_Glasses/9.png',
      '10': 'Eyes/Swirly_Glasses/10.png',
      '11': 'Eyes/Swirly_Glasses/11.png',
    },
  },
  Head: {
    Babushka: {
      '1': 'Head/Babushka/1.png',
      '2': 'Head/Babushka/2.png',
      '3': 'Head/Babushka/3.png',
      '4': 'Head/Babushka/4.png',
      '5': 'Head/Babushka/5.png',
      '6': 'Head/Babushka/6.png',
      '7': 'Head/Babushka/7.png',
      '8': 'Head/Babushka/8.png',
      '9': 'Head/Babushka/9.png',
      '10': 'Head/Babushka/10.png',
      '9_1': 'Head/Babushka/9_1.png',
    },
    Bed_Head: {
      '1': 'Head/Bed_Head/1.png',
      '2': 'Head/Bed_Head/2.png',
      '3': 'Head/Bed_Head/3.png',
      '4': 'Head/Bed_Head/4.png',
      '5': 'Head/Bed_Head/5.png',
      '6': 'Head/Bed_Head/6.png',
      '7': 'Head/Bed_Head/7.png',
      '8': 'Head/Bed_Head/8.png',
      '9': 'Head/Bed_Head/9.png',
      '10': 'Head/Bed_Head/10.png',
      '11': 'Head/Bed_Head/11.png',
      '12': 'Head/Bed_Head/12.png',
      '13': 'Head/Bed_Head/13.png',
      '14': 'Head/Bed_Head/14.png',
    },
    Bleached: {
      '1': 'Head/Bleached/1.png',
      '2': 'Head/Bleached/2.png',
      '3': 'Head/Bleached/3.png',
      '4': 'Head/Bleached/4.png',
      '5': 'Head/Bleached/5.png',
      '6': 'Head/Bleached/6.png',
      '7': 'Head/Bleached/7.png',
    },
    Bleached_Curls: {
      '1': 'Head/Bleached_Curls/1.png',
      '2': 'Head/Bleached_Curls/2.png',
      '3': 'Head/Bleached_Curls/3.png',
      '4': 'Head/Bleached_Curls/4.png',
      '5': 'Head/Bleached_Curls/5.png',
      '6': 'Head/Bleached_Curls/6.png',
      '7': 'Head/Bleached_Curls/7.png',
      '8': 'Head/Bleached_Curls/8.png',
      '9': 'Head/Bleached_Curls/9.png',
      '10': 'Head/Bleached_Curls/10.png',
      '11': 'Head/Bleached_Curls/11.png',
      '12': 'Head/Bleached_Curls/12.png',
      '13': 'Head/Bleached_Curls/13.png',
      '14': 'Head/Bleached_Curls/14.png',
      '15': 'Head/Bleached_Curls/15.png',
      '16': 'Head/Bleached_Curls/16.png',
      '17': 'Head/Bleached_Curls/17.png',
    },
    Bloody_Horns: {
      '1': 'Head/Bloody_Horns/1.png',
      '2': 'Head/Bloody_Horns/2.png',
      '3': 'Head/Bloody_Horns/3.png',
      '4': 'Head/Bloody_Horns/4.png',
      '5': 'Head/Bloody_Horns/5.png',
      '6': 'Head/Bloody_Horns/6.png',
      '7': 'Head/Bloody_Horns/7.png',
      '8': 'Head/Bloody_Horns/8.png',
      '9': 'Head/Bloody_Horns/9.png',
      '10': 'Head/Bloody_Horns/10.png',
      '11': 'Head/Bloody_Horns/11.png',
      '12': 'Head/Bloody_Horns/12.png',
      '13': 'Head/Bloody_Horns/13.png',
      '14': 'Head/Bloody_Horns/14.png',
    },
    Curly: {
      '1': 'Head/Curly/1.png',
      '2': 'Head/Curly/2.png',
      '3': 'Head/Curly/3.png',
      '4': 'Head/Curly/4.png',
      '5': 'Head/Curly/5.png',
      '6': 'Head/Curly/6.png',
      '7': 'Head/Curly/7.png',
      '8': 'Head/Curly/8.png',
    },
    DeGod_Pro_Trucker: {
      '1': 'Head/DeGod_Pro_Trucker/1.png',
      '2': 'Head/DeGod_Pro_Trucker/2.png',
      '3': 'Head/DeGod_Pro_Trucker/3.png',
      '4': 'Head/DeGod_Pro_Trucker/4.png',
      '5': 'Head/DeGod_Pro_Trucker/5.png',
      '6': 'Head/DeGod_Pro_Trucker/6.png',
      '7': 'Head/DeGod_Pro_Trucker/7.png',
      '8': 'Head/DeGod_Pro_Trucker/8.png',
      '9': 'Head/DeGod_Pro_Trucker/9.png',
      '10': 'Head/DeGod_Pro_Trucker/10.png',
      '11': 'Head/DeGod_Pro_Trucker/11.png',
      '12': 'Head/DeGod_Pro_Trucker/12.png',
      '13': 'Head/DeGod_Pro_Trucker/13.png',
    },
    DeGucci_Bucket_Hat: {
      '1': 'Head/DeGucci_Bucket_Hat/1.png',
      '2': 'Head/DeGucci_Bucket_Hat/2.png',
      '3': 'Head/DeGucci_Bucket_Hat/3.png',
      '4': 'Head/DeGucci_Bucket_Hat/4.png',
      '5': 'Head/DeGucci_Bucket_Hat/5.png',
      '6': 'Head/DeGucci_Bucket_Hat/6.png',
    },
    Dimmadome_Top_Hat: {
      '1': 'Head/Dimmadome_Top_Hat/1.png',
      '2': 'Head/Dimmadome_Top_Hat/2.png',
      '3': 'Head/Dimmadome_Top_Hat/3.png',
      '4': 'Head/Dimmadome_Top_Hat/4.png',
      '5': 'Head/Dimmadome_Top_Hat/5.png',
      '6': 'Head/Dimmadome_Top_Hat/6.png',
      '7': 'Head/Dimmadome_Top_Hat/7.png',
    },
    Exposed_Brain: {
      '1': 'Head/Exposed_Brain/1.png',
      '2': 'Head/Exposed_Brain/2.png',
      '3': 'Head/Exposed_Brain/3.png',
      '4': 'Head/Exposed_Brain/4.png',
    },
    Fade: {
      '1': 'Head/Fade/1.png',
      '2': 'Head/Fade/2.png',
      '3': 'Head/Fade/3.png',
      '4': 'Head/Fade/4.png',
      '5': 'Head/Fade/5.png',
      '6': 'Head/Fade/6.png',
    },
    Godfro: {
      '1': 'Head/Godfro/1.png',
      '2': 'Head/Godfro/2.png',
      '3': 'Head/Godfro/3.png',
      '4': 'Head/Godfro/4.png',
      '5': 'Head/Godfro/5.png',
    },
    Godhawk: {
      '1': 'Head/Godhawk/1.png',
      '2': 'Head/Godhawk/2.png',
      '3': 'Head/Godhawk/3.png',
      '4': 'Head/Godhawk/4.png',
      '5': 'Head/Godhawk/5.png',
      '6': 'Head/Godhawk/6.png',
      '7': 'Head/Godhawk/7.png',
      '8': 'Head/Godhawk/8.png',
      '9': 'Head/Godhawk/9.png',
    },
    Godlielocks: {
      '1': 'Head/Godlielocks/1.png',
      '2': 'Head/Godlielocks/2.png',
      '3': 'Head/Godlielocks/3.png',
      '4': 'Head/Godlielocks/4.png',
      '5': 'Head/Godlielocks/5.png',
      '6': 'Head/Godlielocks/6.png',
    },
    Gold_Leaf_Laurel: {
      '1': 'Head/Gold_Leaf_Laurel/1.png',
      '2': 'Head/Gold_Leaf_Laurel/2.png',
      '3': 'Head/Gold_Leaf_Laurel/3.png',
      '4': 'Head/Gold_Leaf_Laurel/4.png',
      '5': 'Head/Gold_Leaf_Laurel/5.png',
      '6': 'Head/Gold_Leaf_Laurel/6.png',
      '7': 'Head/Gold_Leaf_Laurel/7.png',
    },
    Headband: {
      '1': 'Head/Headband/1.png',
      '2': 'Head/Headband/2.png',
      '3': 'Head/Headband/3.png',
      '4': 'Head/Headband/4.png',
      '5': 'Head/Headband/5.png',
      '6': 'Head/Headband/6.png',
      '7': 'Head/Headband/7.png',
      '8': 'Head/Headband/8.png',
      '9': 'Head/Headband/9.png',
    },
    Heavenly_Crown: {
      '1': 'Head/Heavenly_Crown/1.png',
      '2': 'Head/Heavenly_Crown/2.png',
      '3': 'Head/Heavenly_Crown/3.png',
      '4': 'Head/Heavenly_Crown/4.png',
      '5': 'Head/Heavenly_Crown/5.png',
      '6': 'Head/Heavenly_Crown/6.png',
      '7': 'Head/Heavenly_Crown/7.png',
      '8': 'Head/Heavenly_Crown/8.png',
      '9': 'Head/Heavenly_Crown/9.png',
      '10': 'Head/Heavenly_Crown/10.png',
    },
    Hippie_Hair: {
      '1': 'Head/Hippie_Hair/1.png',
      '2': 'Head/Hippie_Hair/2.png',
      '3': 'Head/Hippie_Hair/3.png',
      '4': 'Head/Hippie_Hair/4.png',
      '5': 'Head/Hippie_Hair/5.png',
      '6': 'Head/Hippie_Hair/6.png',
      '7': 'Head/Hippie_Hair/7.png',
      '8': 'Head/Hippie_Hair/8.png',
      '6_1': 'Head/Hippie_Hair/6_1.png',
    },
    Leaf_Laurel: {
      '1': 'Head/Leaf_Laurel/1.png',
      '2': 'Head/Leaf_Laurel/2.png',
      '3': 'Head/Leaf_Laurel/3.png',
      '4': 'Head/Leaf_Laurel/4.png',
      '5': 'Head/Leaf_Laurel/5.png',
      '6': 'Head/Leaf_Laurel/6.png',
    },
    Mad_Scientist: {
      '1': 'Head/Mad_Scientist/1.png',
      '2': 'Head/Mad_Scientist/2.png',
      '3': 'Head/Mad_Scientist/3.png',
      '4': 'Head/Mad_Scientist/4.png',
      '5': 'Head/Mad_Scientist/5.png',
      '6': 'Head/Mad_Scientist/6.png',
      '7': 'Head/Mad_Scientist/7.png',
    },
    Medusa: {
      '1': 'Head/Medusa/1.png',
      '2': 'Head/Medusa/2.png',
      '3': 'Head/Medusa/3.png',
      '4': 'Head/Medusa/4.png',
      '5': 'Head/Medusa/5.png',
      '6': 'Head/Medusa/6.png',
      '7': 'Head/Medusa/7.png',
      '8': 'Head/Medusa/8.png',
      '9': 'Head/Medusa/9.png',
      '10': 'Head/Medusa/10.png',
      '11': 'Head/Medusa/11.png',
      '12': 'Head/Medusa/12.png',
    },
    Mickey_DeGods_Visor: {
      '1': 'Head/Mickey_DeGods_Visor/1.png',
      '2': 'Head/Mickey_DeGods_Visor/2.png',
      '3': 'Head/Mickey_DeGods_Visor/3.png',
      '4': 'Head/Mickey_DeGods_Visor/4.png',
      '5': 'Head/Mickey_DeGods_Visor/5.png',
      '6': 'Head/Mickey_DeGods_Visor/6.png',
      '7': 'Head/Mickey_DeGods_Visor/7.png',
      '8': 'Head/Mickey_DeGods_Visor/8.png',
      '9': 'Head/Mickey_DeGods_Visor/9.png',
      '10': 'Head/Mickey_DeGods_Visor/10.png',
      '11': 'Head/Mickey_DeGods_Visor/11.png',
    },
    Mullet: {
      '1': 'Head/Mullet/1.png',
      '2': 'Head/Mullet/2.png',
      '3': 'Head/Mullet/3.png',
      '4': 'Head/Mullet/4.png',
      '5': 'Head/Mullet/5.png',
      '6': 'Head/Mullet/6.png',
      '7': 'Head/Mullet/7.png',
      '8': 'Head/Mullet/8.png',
      '9': 'Head/Mullet/9.png',
      '11': 'Head/Mullet/11.png',
      '12': 'Head/Mullet/12.png',
    },
    Mushroom_Head: {
      '1': 'Head/Mushroom_Head/1.png',
      '2': 'Head/Mushroom_Head/2.png',
      '3': 'Head/Mushroom_Head/3.png',
      '4': 'Head/Mushroom_Head/4.png',
      '5': 'Head/Mushroom_Head/5.png',
      '6': 'Head/Mushroom_Head/6.png',
      '7': 'Head/Mushroom_Head/7.png',
      '8': 'Head/Mushroom_Head/8.png',
      '8_1': 'Head/Mushroom_Head/8_1.png',
    },
    Mythic_Halo: {
      '1': 'Head/Mythic_Halo/1.png',
      '2': 'Head/Mythic_Halo/2.png',
      '3': 'Head/Mythic_Halo/3.png',
      '4': 'Head/Mythic_Halo/4.png',
      '5': 'Head/Mythic_Halo/5.png',
      '6': 'Head/Mythic_Halo/6.png',
      '7': 'Head/Mythic_Halo/7.png',
      '8': 'Head/Mythic_Halo/8.png',
      '9': 'Head/Mythic_Halo/9.png',
      '10': 'Head/Mythic_Halo/10.png',
      '11': 'Head/Mythic_Halo/11.png',
      '12': 'Head/Mythic_Halo/12.png',
    },
    Mythic_Helmet: {
      '1': 'Head/Mythic_Helmet/1.png',
      '2': 'Head/Mythic_Helmet/2.png',
      '3': 'Head/Mythic_Helmet/3.png',
      '4': 'Head/Mythic_Helmet/4.png',
      '5': 'Head/Mythic_Helmet/5.png',
      '6': 'Head/Mythic_Helmet/6.png',
      '7': 'Head/Mythic_Helmet/7.png',
      '8': 'Head/Mythic_Helmet/8.png',
      '9': 'Head/Mythic_Helmet/9.png',
      '10': 'Head/Mythic_Helmet/10.png',
      '11': 'Head/Mythic_Helmet/11.png',
      '12': 'Head/Mythic_Helmet/12.png',
    },
    Pharaohs_Headdress: {
      '1': 'Head/Pharaohs_Headdress/1.png',
      '2': 'Head/Pharaohs_Headdress/2.png',
      '3': 'Head/Pharaohs_Headdress/3.png',
      '4': 'Head/Pharaohs_Headdress/4.png',
      '5': 'Head/Pharaohs_Headdress/5.png',
      '6': 'Head/Pharaohs_Headdress/6.png',
      '7': 'Head/Pharaohs_Headdress/7.png',
      '8': 'Head/Pharaohs_Headdress/8.png',
    },
    Plank: {
      '1': 'Head/Plank/1.png',
      '2': 'Head/Plank/2.png',
      '3': 'Head/Plank/3.png',
      '4': 'Head/Plank/4.png',
      '5': 'Head/Plank/5.png',
      '6': 'Head/Plank/6.png',
    },
    Prince_Hair: {
      '1': 'Head/Prince_Hair/1.png',
      '2': 'Head/Prince_Hair/2.png',
      '3': 'Head/Prince_Hair/3.png',
      '4': 'Head/Prince_Hair/4.png',
      '5': 'Head/Prince_Hair/5.png',
      '6': 'Head/Prince_Hair/6.png',
      '7': 'Head/Prince_Hair/7.png',
      '8': 'Head/Prince_Hair/8.png',
      '9': 'Head/Prince_Hair/9.png',
      '10': 'Head/Prince_Hair/10.png',
      '11': 'Head/Prince_Hair/11.png',
      '12': 'Head/Prince_Hair/12.png',
    },
    Propeller_Hat: {
      '1': 'Head/Propeller_Hat/1.png',
      '2': 'Head/Propeller_Hat/2.png',
      '3': 'Head/Propeller_Hat/3.png',
      '4': 'Head/Propeller_Hat/4.png',
      '5': 'Head/Propeller_Hat/5.png',
      '6': 'Head/Propeller_Hat/6.png',
      '7': 'Head/Propeller_Hat/7.png',
      '8': 'Head/Propeller_Hat/8.png',
      '9': 'Head/Propeller_Hat/9.png',
      '10': 'Head/Propeller_Hat/10.png',
      '11': 'Head/Propeller_Hat/11.png',
      '12': 'Head/Propeller_Hat/12.png',
      '13': 'Head/Propeller_Hat/13.png',
    },
    Rainbow_Definitely_Not_A_Dildo: {
      '1': 'Head/Rainbow_Definitely_Not_A_Dildo/1.png',
      '2': 'Head/Rainbow_Definitely_Not_A_Dildo/2.png',
      '3': 'Head/Rainbow_Definitely_Not_A_Dildo/3.png',
      '4': 'Head/Rainbow_Definitely_Not_A_Dildo/4.png',
      '5': 'Head/Rainbow_Definitely_Not_A_Dildo/5.png',
      '6': 'Head/Rainbow_Definitely_Not_A_Dildo/6.png',
      '7': 'Head/Rainbow_Definitely_Not_A_Dildo/7.png',
      '8': 'Head/Rainbow_Definitely_Not_A_Dildo/8.png',
      '9': 'Head/Rainbow_Definitely_Not_A_Dildo/9.png',
      '10': 'Head/Rainbow_Definitely_Not_A_Dildo/10.png',
      '11': 'Head/Rainbow_Definitely_Not_A_Dildo/11.png',
      '12': 'Head/Rainbow_Definitely_Not_A_Dildo/12.png',
      '13': 'Head/Rainbow_Definitely_Not_A_Dildo/13.png',
    },
    Skull_Mask: {
      '1': 'Head/Skull_Mask/1.png',
      '2': 'Head/Skull_Mask/2.png',
      '3': 'Head/Skull_Mask/3.png',
      '4': 'Head/Skull_Mask/4.png',
      '5': 'Head/Skull_Mask/5.png',
      '6': 'Head/Skull_Mask/6.png',
      '7': 'Head/Skull_Mask/7.png',
      '8': 'Head/Skull_Mask/8.png',
    },
    Ushanka: {
      '1': 'Head/Ushanka/1.png',
      '2': 'Head/Ushanka/2.png',
      '3': 'Head/Ushanka/3.png',
      '4': 'Head/Ushanka/4.png',
      '5': 'Head/Ushanka/5.png',
      '6': 'Head/Ushanka/6.png',
      '7': 'Head/Ushanka/7.png',
      '8': 'Head/Ushanka/8.png',
      '9': 'Head/Ushanka/9.png',
      '10': 'Head/Ushanka/10.png',
      '11': 'Head/Ushanka/11.png',
      '12': 'Head/Ushanka/12.png',
    },
    Winged_Helmet: {
      '1': 'Head/Winged_Helmet/1.png',
      '2': 'Head/Winged_Helmet/2.png',
      '3': 'Head/Winged_Helmet/3.png',
      '4': 'Head/Winged_Helmet/4.png',
      '5': 'Head/Winged_Helmet/5.png',
      '6': 'Head/Winged_Helmet/6.png',
      '7': 'Head/Winged_Helmet/7.png',
      '8': 'Head/Winged_Helmet/8.png',
      '9': 'Head/Winged_Helmet/9.png',
      '10': 'Head/Winged_Helmet/10.png',
      '11': 'Head/Winged_Helmet/11.png',
      '6_1': 'Head/Winged_Helmet/6_1.png',
    },
  },
  Mouth: {
    Cigarette: {
      '1': 'Mouth/Cigarette/1.png',
      '2': 'Mouth/Cigarette/2.png',
      '3': 'Mouth/Cigarette/3.png',
      '4': 'Mouth/Cigarette/4.png',
      '5': 'Mouth/Cigarette/5.png',
      '6': 'Mouth/Cigarette/6.png',
    },
    Clown_Nose: {
      '1': 'Mouth/Clown_Nose/1.png',
      '2': 'Mouth/Clown_Nose/2.png',
      '3': 'Mouth/Clown_Nose/3.png',
      '4': 'Mouth/Clown_Nose/4.png',
      '5': 'Mouth/Clown_Nose/5.png',
      '6': 'Mouth/Clown_Nose/6.png',
    },
    Fruit_Roll_Up: {
      '1': 'Mouth/Fruit_Roll_Up/1.png',
      '2': 'Mouth/Fruit_Roll_Up/2.png',
      '3': 'Mouth/Fruit_Roll_Up/3.png',
      '4': 'Mouth/Fruit_Roll_Up/4.png',
      '5': 'Mouth/Fruit_Roll_Up/5.png',
      '6': 'Mouth/Fruit_Roll_Up/6.png',
      '7': 'Mouth/Fruit_Roll_Up/7.png',
    },
    Goatee: {
      '1': 'Mouth/Goatee/1.png',
      '2': 'Mouth/Goatee/2.png',
      '3': 'Mouth/Goatee/3.png',
      '4': 'Mouth/Goatee/4.png',
      '5': 'Mouth/Goatee/5.png',
      '6': 'Mouth/Goatee/6.png',
    },
    Heavenly_Wood: {
      '1': 'Mouth/Heavenly_Wood/1.png',
      '2': 'Mouth/Heavenly_Wood/2.png',
      '3': 'Mouth/Heavenly_Wood/3.png',
      '4': 'Mouth/Heavenly_Wood/4.png',
      '5': 'Mouth/Heavenly_Wood/5.png',
    },
    Hipster_Beard: {
      '1': 'Mouth/Hipster_Beard/1.png',
      '2': 'Mouth/Hipster_Beard/2.png',
      '3': 'Mouth/Hipster_Beard/3.png',
      '4': 'Mouth/Hipster_Beard/4.png',
      '5': 'Mouth/Hipster_Beard/5.png',
      '6': 'Mouth/Hipster_Beard/6.png',
      '7': 'Mouth/Hipster_Beard/7.png',
      '8': 'Mouth/Hipster_Beard/8.png',
    },
    Party_Blower: {
      '1': 'Mouth/Party_Blower/1.png',
      '2': 'Mouth/Party_Blower/2.png',
      '3': 'Mouth/Party_Blower/3.png',
      '4': 'Mouth/Party_Blower/4.png',
      '5': 'Mouth/Party_Blower/5.png',
      '6': 'Mouth/Party_Blower/6.png',
      '7': 'Mouth/Party_Blower/7.png',
    },
    Porn_Stashe: {
      '1': 'Mouth/Porn_Stashe/1.png',
      '2': 'Mouth/Porn_Stashe/2.png',
      '3': 'Mouth/Porn_Stashe/3.png',
      '4': 'Mouth/Porn_Stashe/4.png',
      '5': 'Mouth/Porn_Stashe/5.png',
    },
    Santa_Beard: {
      '1': 'Mouth/Santa_Beard/1.png',
      '2': 'Mouth/Santa_Beard/2.png',
      '3': 'Mouth/Santa_Beard/3.png',
      '4': 'Mouth/Santa_Beard/4.png',
      '5': 'Mouth/Santa_Beard/5.png',
    },
    Smoke_Ring: {
      '1': 'Mouth/Smoke_Ring/1.png',
      '2': 'Mouth/Smoke_Ring/2.png',
      '3': 'Mouth/Smoke_Ring/3.png',
      '4': 'Mouth/Smoke_Ring/4.png',
      '5': 'Mouth/Smoke_Ring/5.png',
    },
    Vape_God: {
      '1': 'Mouth/Vape_God/1.png',
      '2': 'Mouth/Vape_God/2.png',
      '3': 'Mouth/Vape_God/3.png',
      '4': 'Mouth/Vape_God/4.png',
    },
  },
  Neck: {
    Cannibal_Necklace: {
      '1': 'Neck/Cannibal_Necklace/1.png',
      '2': 'Neck/Cannibal_Necklace/2.png',
      '3': 'Neck/Cannibal_Necklace/3.png',
      '4': 'Neck/Cannibal_Necklace/4.png',
      '5': 'Neck/Cannibal_Necklace/5.png',
      '6': 'Neck/Cannibal_Necklace/6.png',
    },
    Christmas_Lights_Chain: {
      '1': 'Neck/Christmas_Lights_Chain/1.png',
      '2': 'Neck/Christmas_Lights_Chain/2.png',
      '3': 'Neck/Christmas_Lights_Chain/3.png',
      '4': 'Neck/Christmas_Lights_Chain/4.png',
      '5': 'Neck/Christmas_Lights_Chain/5.png',
      '6': 'Neck/Christmas_Lights_Chain/6.png',
    },
    Diamond_Necklace: {
      '1': 'Neck/Diamond_Necklace/1.png',
      '2': 'Neck/Diamond_Necklace/2.png',
      '3': 'Neck/Diamond_Necklace/3.png',
      '4': 'Neck/Diamond_Necklace/4.png',
      '5': 'Neck/Diamond_Necklace/5.png',
      '6': 'Neck/Diamond_Necklace/6.png',
    },
    Double_Diamond_Necklace: {
      '1': 'Neck/Double_Diamond_Necklace/1.png',
      '2': 'Neck/Double_Diamond_Necklace/2.png',
      '3': 'Neck/Double_Diamond_Necklace/3.png',
      '4': 'Neck/Double_Diamond_Necklace/4.png',
      '5': 'Neck/Double_Diamond_Necklace/5.png',
    },
    Friendship_Necklace: {
      '1': 'Neck/Friendship_Necklace/1.png',
      '2': 'Neck/Friendship_Necklace/2.png',
      '3': 'Neck/Friendship_Necklace/3.png',
      '4': 'Neck/Friendship_Necklace/4.png',
    },
    Gold_Chain: {
      '1': 'Neck/Gold_Chain/1.png',
      '2': 'Neck/Gold_Chain/2.png',
      '3': 'Neck/Gold_Chain/3.png',
      '4': 'Neck/Gold_Chain/4.png',
      '5': 'Neck/Gold_Chain/5.png',
    },
    Louis_Scarf: {
      '1': 'Neck/Louis_Scarf/1.png',
      '2': 'Neck/Louis_Scarf/2.png',
      '3': 'Neck/Louis_Scarf/3.png',
      '4': 'Neck/Louis_Scarf/4.png',
      '5': 'Neck/Louis_Scarf/5.png',
      '6': 'Neck/Louis_Scarf/6.png',
    },
    Mythic_Mamba: {
      '1': 'Neck/Mythic_Mamba/1.png',
      '2': 'Neck/Mythic_Mamba/2.png',
      '3': 'Neck/Mythic_Mamba/3.png',
      '4': 'Neck/Mythic_Mamba/4.png',
      '5': 'Neck/Mythic_Mamba/5.png',
      '6': 'Neck/Mythic_Mamba/6.png',
      '7': 'Neck/Mythic_Mamba/7.png',
      '8': 'Neck/Mythic_Mamba/8.png',
      '9': 'Neck/Mythic_Mamba/9.png',
      '10': 'Neck/Mythic_Mamba/10.png',
      '11': 'Neck/Mythic_Mamba/11.png',
      '12': 'Neck/Mythic_Mamba/12.png',
    },
    Paperclip_Necklace: {
      '1': 'Neck/Paperclip_Necklace/1.png',
      '2': 'Neck/Paperclip_Necklace/2.png',
      '3': 'Neck/Paperclip_Necklace/3.png',
      '4': 'Neck/Paperclip_Necklace/4.png',
      '5': 'Neck/Paperclip_Necklace/5.png',
    },
    Pimp_Chain: {
      '1': 'Neck/Pimp_Chain/1.png',
      '2': 'Neck/Pimp_Chain/2.png',
      '3': 'Neck/Pimp_Chain/3.png',
      '4': 'Neck/Pimp_Chain/4.png',
      '5': 'Neck/Pimp_Chain/5.png',
    },
    Silver_Chain: {
      '1': 'Neck/Silver_Chain/1.png',
      '2': 'Neck/Silver_Chain/2.png',
      '3': 'Neck/Silver_Chain/3.png',
      '4': 'Neck/Silver_Chain/4.png',
      '5': 'Neck/Silver_Chain/5.png',
    },
    Solana_Chain: {
      '1': 'Neck/Solana_Chain/1.png',
      '2': 'Neck/Solana_Chain/2.png',
      '3': 'Neck/Solana_Chain/3.png',
      '4': 'Neck/Solana_Chain/4.png',
      '5': 'Neck/Solana_Chain/5.png',
      '6': 'Neck/Solana_Chain/6.png',
      '7': 'Neck/Solana_Chain/7.png',
    },
  },
  Skins: {
    Acid: {
      '.DS_Store': 'Skins/Acid/.DS_Store',
      'Acid 1': 'Skins/Acid/Acid 1.png',
      'Acid 2': 'Skins/Acid/Acid 2.png',
      'Acid 3': 'Skins/Acid/Acid 3.png',
      'Acid 4': 'Skins/Acid/Acid 4.png',
      'Acid 5': 'Skins/Acid/Acid 5.png',
      'Acid 6': 'Skins/Acid/Acid 6.png',
      'Acid 7': 'Skins/Acid/Acid 7.png',
      'Acid 8': 'Skins/Acid/Acid 8.png',
    },
    Ape: {
      '.DS_Store': 'Skins/Ape/.DS_Store',
      'Ape 1': 'Skins/Ape/Ape 1.png',
      'Ape 2': 'Skins/Ape/Ape 2.png',
      'Ape 3': 'Skins/Ape/Ape 3.png',
      'Ape 4': 'Skins/Ape/Ape 4.png',
      'Ape 5': 'Skins/Ape/Ape 5.png',
      'Ape 6': 'Skins/Ape/Ape 6.png',
      'Ape 7': 'Skins/Ape/Ape 7.png',
      'Ape 8': 'Skins/Ape/Ape 8.png',
      'Ape 9': 'Skins/Ape/Ape 9.png',
    },
    Blue_sky: {
      '.DS_Store': 'Skins/Blue_sky/.DS_Store',
      'Blue Sky 1': 'Skins/Blue_sky/Blue Sky 1.png',
      'Blue Sky 2': 'Skins/Blue_sky/Blue Sky 2.png',
      'Blue Sky 3': 'Skins/Blue_sky/Blue Sky 3.png',
      'Blue Sky 4': 'Skins/Blue_sky/Blue Sky 4.png',
      'Blue Sky 5': 'Skins/Blue_sky/Blue Sky 5.png',
      'Blue Sky 6': 'Skins/Blue_sky/Blue Sky 6.png',
      'Blue Sky 7': 'Skins/Blue_sky/Blue Sky 7.png',
      'Blue Sky 8': 'Skins/Blue_sky/Blue Sky 8.png',
    },
    Gold: {
      '.DS_Store': 'Skins/Gold/.DS_Store',
      'Gold 1': 'Skins/Gold/Gold 1.png',
      'Gold 2': 'Skins/Gold/Gold 2.png',
      'Gold 3': 'Skins/Gold/Gold 3.png',
      'Gold 4': 'Skins/Gold/Gold 4.png',
      'Gold 5': 'Skins/Gold/Gold 5.png',
      'Gold 6': 'Skins/Gold/Gold 6.png',
      'Gold 7': 'Skins/Gold/Gold 7.png',
    },
    Ice: {
      '.DS_Store': 'Skins/Ice/.DS_Store',
      'Ice 1': 'Skins/Ice/Ice 1.png',
      'Ice 10': 'Skins/Ice/Ice 10.png',
      'Ice 11': 'Skins/Ice/Ice 11.png',
      'Ice 12': 'Skins/Ice/Ice 12.png',
      'Ice 13': 'Skins/Ice/Ice 13.png',
      'Ice 2': 'Skins/Ice/Ice 2.png',
      'Ice 3': 'Skins/Ice/Ice 3.png',
      'Ice 4': 'Skins/Ice/Ice 4.png',
      'Ice 5': 'Skins/Ice/Ice 5.png',
      'Ice 6': 'Skins/Ice/Ice 6.png',
      'Ice 7': 'Skins/Ice/Ice 7.png',
      'Ice 8': 'Skins/Ice/Ice 8.png',
      'Ice 9': 'Skins/Ice/Ice 9.png',
    },
    Joker: {
      '.DS_Store': 'Skins/Joker/.DS_Store',
      'Joker 1': 'Skins/Joker/Joker 1.png',
      'Joker 2': 'Skins/Joker/Joker 2.png',
      'Joker 3': 'Skins/Joker/Joker 3.png',
      'Joker 4': 'Skins/Joker/Joker 4.png',
      'Joker 5': 'Skins/Joker/Joker 5.png',
      'Joker 6': 'Skins/Joker/Joker 6.png',
      'Joker 7': 'Skins/Joker/Joker 7.png',
    },
    Lavender_stripe: {
      '.DS_Store': 'Skins/Lavender_stripe/.DS_Store',
      'Lavender Stripe 1': 'Skins/Lavender_stripe/Lavender Stripe 1.png',
      'Lavender Stripe 2': 'Skins/Lavender_stripe/Lavender Stripe 2.png',
      'Lavender Stripe 3': 'Skins/Lavender_stripe/Lavender Stripe 3.png',
      'Lavender Stripe 4': 'Skins/Lavender_stripe/Lavender Stripe 4.png',
      'Lavender Stripe 5': 'Skins/Lavender_stripe/Lavender Stripe 5.png',
      'Lavender Stripe 6': 'Skins/Lavender_stripe/Lavender Stripe 6.png',
      'Lavender Stripe 7': 'Skins/Lavender_stripe/Lavender Stripe 7.png',
    },
    Leopard: {
      '.DS_Store': 'Skins/Leopard/.DS_Store',
      'Leopard 1': 'Skins/Leopard/Leopard 1.png',
      'Leopard 2': 'Skins/Leopard/Leopard 2.png',
      'Leopard 3': 'Skins/Leopard/Leopard 3.png',
      'Leopard 4': 'Skins/Leopard/Leopard 4.png',
      'Leopard 5': 'Skins/Leopard/Leopard 5.png',
      'Leopard 6': 'Skins/Leopard/Leopard 6.png',
      'Leopard 7': 'Skins/Leopard/Leopard 7.png',
    },
    Marble: {
      '.DS_Store': 'Skins/Marble/.DS_Store',
      'Marble 1': 'Skins/Marble/Marble 1.png',
      'Marble 2': 'Skins/Marble/Marble 2.png',
      'Marble 3': 'Skins/Marble/Marble 3.png',
      'Marble 4': 'Skins/Marble/Marble 4.png',
      'Marble 5': 'Skins/Marble/Marble 5.png',
      'Marble 6': 'Skins/Marble/Marble 6.png',
      'Marble 7': 'Skins/Marble/Marble 7.png',
    },
    Navi: {
      '.DS_Store': 'Skins/Navi/.DS_Store',
      'Navi 1': 'Skins/Navi/Navi 1.png',
      'Navi 2': 'Skins/Navi/Navi 2.png',
      'Navi 3': 'Skins/Navi/Navi 3.png',
      'Navi 4': 'Skins/Navi/Navi 4.png',
      'Navi 5': 'Skins/Navi/Navi 5.png',
      'Navi 6': 'Skins/Navi/Navi 6.png',
      'Navi 7': 'Skins/Navi/Navi 7.png',
      'Navi 8': 'Skins/Navi/Navi 8.png',
      'Navi 9': 'Skins/Navi/Navi 9.png',
    },
    Nebula: {
      '.DS_Store': 'Skins/Nebula/.DS_Store',
      'Nebula 1': 'Skins/Nebula/Nebula 1.png',
      'Nebula 10': 'Skins/Nebula/Nebula 10.png',
      'Nebula 11': 'Skins/Nebula/Nebula 11.png',
      'Nebula 12': 'Skins/Nebula/Nebula 12.png',
      'Nebula 13': 'Skins/Nebula/Nebula 13.png',
      'Nebula 14': 'Skins/Nebula/Nebula 14.png',
      'Nebula 2': 'Skins/Nebula/Nebula 2.png',
      'Nebula 3': 'Skins/Nebula/Nebula 3.png',
      'Nebula 4': 'Skins/Nebula/Nebula 4.png',
      'Nebula 5': 'Skins/Nebula/Nebula 5.png',
      'Nebula 6': 'Skins/Nebula/Nebula 6.png',
      'Nebula 7': 'Skins/Nebula/Nebula 7.png',
      'Nebula 8': 'Skins/Nebula/Nebula 8.png',
      'Nebula 9': 'Skins/Nebula/Nebula 9.png',
    },
    Pastel: {
      '.DS_Store': 'Skins/Pastel/.DS_Store',
      'Pastel 1': 'Skins/Pastel/Pastel 1.png',
      'Pastel 2': 'Skins/Pastel/Pastel 2.png',
      'Pastel 3': 'Skins/Pastel/Pastel 3.png',
      'Pastel 4': 'Skins/Pastel/Pastel 4.png',
      'Pastel 5': 'Skins/Pastel/Pastel 5.png',
    },
    Pink_granite: {
      '.DS_Store': 'Skins/Pink_granite/.DS_Store',
      'Pink Granite 1': 'Skins/Pink_granite/Pink Granite 1.png',
      'Pink Granite 2': 'Skins/Pink_granite/Pink Granite 2.png',
      'Pink Granite 3': 'Skins/Pink_granite/Pink Granite 3.png',
      'Pink Granite 4': 'Skins/Pink_granite/Pink Granite 4.png',
      'Pink Granite 5': 'Skins/Pink_granite/Pink Granite 5.png',
      'Pink Granite 6': 'Skins/Pink_granite/Pink Granite 6.png',
    },
    Poker: {
      '.DS_Store': 'Skins/Poker/.DS_Store',
      'Poker 1': 'Skins/Poker/Poker 1.png',
      'Poker 2': 'Skins/Poker/Poker 2.png',
      'Poker 3': 'Skins/Poker/Poker 3.png',
      'Poker 4': 'Skins/Poker/Poker 4.png',
    },
    Radioactive: {
      '.DS_Store': 'Skins/Radioactive/.DS_Store',
      'Radioactiive 7': 'Skins/Radioactive/Radioactiive 7.png',
      'Radioactive 1': 'Skins/Radioactive/Radioactive 1.png',
      'Radioactive 10': 'Skins/Radioactive/Radioactive 10.png',
      'Radioactive 11': 'Skins/Radioactive/Radioactive 11.png',
      'Radioactive 2': 'Skins/Radioactive/Radioactive 2.png',
      'Radioactive 3': 'Skins/Radioactive/Radioactive 3.png',
      'Radioactive 4': 'Skins/Radioactive/Radioactive 4.png',
      'Radioactive 5': 'Skins/Radioactive/Radioactive 5.png',
      'Radioactive 6': 'Skins/Radioactive/Radioactive 6.png',
      'Radioactive 8': 'Skins/Radioactive/Radioactive 8.png',
      'Radioactive 9': 'Skins/Radioactive/Radioactive 9.png',
    },
    Solar_spiral: {
      '.DS_Store': 'Skins/Solar_spiral/.DS_Store',
      'Solar Spiral 1': 'Skins/Solar_spiral/Solar Spiral 1.png',
      'Solar Spiral 2': 'Skins/Solar_spiral/Solar Spiral 2.png',
      'Solar Spiral 3': 'Skins/Solar_spiral/Solar Spiral 3.png',
      'Solar Spiral 4': 'Skins/Solar_spiral/Solar Spiral 4.png',
      'Solar Spiral 5': 'Skins/Solar_spiral/Solar Spiral 5.png',
      'Solar Spiral 6': 'Skins/Solar_spiral/Solar Spiral 6.png',
    },
    Transcendent: {
      '.DS_Store': 'Skins/Transcendent/.DS_Store',
      'Transcendent 1': 'Skins/Transcendent/Transcendent 1.png',
      'Transcendent 10': 'Skins/Transcendent/Transcendent 10.png',
      'Transcendent 11': 'Skins/Transcendent/Transcendent 11.png',
      'Transcendent 12': 'Skins/Transcendent/Transcendent 12.png',
      'Transcendent 13': 'Skins/Transcendent/Transcendent 13.png',
      'Transcendent 14': 'Skins/Transcendent/Transcendent 14.png',
      'Transcendent 2': 'Skins/Transcendent/Transcendent 2.png',
      'Transcendent 3': 'Skins/Transcendent/Transcendent 3.png',
      'Transcendent 4': 'Skins/Transcendent/Transcendent 4.png',
      'Transcendent 5': 'Skins/Transcendent/Transcendent 5.png',
      'Transcendent 6': 'Skins/Transcendent/Transcendent 6.png',
      'Transcendent 7': 'Skins/Transcendent/Transcendent 7.png',
      'Transcendent 8': 'Skins/Transcendent/Transcendent 8.png',
      'Transcendent 9': 'Skins/Transcendent/Transcendent 9.png',
    },
    Turquoise: {
      '.DS_Store': 'Skins/Turquoise/.DS_Store',
      'Turquoise 1': 'Skins/Turquoise/Turquoise 1.png',
      'Turquoise 2': 'Skins/Turquoise/Turquoise 2.png',
      'Turquoise 3': 'Skins/Turquoise/Turquoise 3.png',
      'Turquoise 4': 'Skins/Turquoise/Turquoise 4.png',
      'Turquoise 5': 'Skins/Turquoise/Turquoise 5.png',
      'Turquoise 6': 'Skins/Turquoise/Turquoise 6.png',
      'Turquoise 7': 'Skins/Turquoise/Turquoise 7.png',
      'Turquoise 8': 'Skins/Turquoise/Turquoise 8.png',
    },
    'X-ray': {
      '.DS_Store': 'Skins/X-ray/.DS_Store',
      'X-ray 1': 'Skins/X-ray/X-ray 1.png',
      'X-ray 2': 'Skins/X-ray/X-ray 2.png',
      'X-ray 3': 'Skins/X-ray/X-ray 3.png',
      'X-ray 4': 'Skins/X-ray/X-ray 4.png',
      'X-ray 5': 'Skins/X-ray/X-ray 5.png',
      'X-ray 6': 'Skins/X-ray/X-ray 6.png',
    },
    Zebra: {
      '.DS_Store': 'Skins/Zebra/.DS_Store',
      'Zebra 1': 'Skins/Zebra/Zebra 1.png',
      'Zebra 10': 'Skins/Zebra/Zebra 10.png',
      'Zebra 2': 'Skins/Zebra/Zebra 2.png',
      'Zebra 3': 'Skins/Zebra/Zebra 3.png',
      'Zebra 4': 'Skins/Zebra/Zebra 4.png',
      'Zebra 5': 'Skins/Zebra/Zebra 5.png',
      'Zebra 6': 'Skins/Zebra/Zebra 6.png',
      'Zebra 7': 'Skins/Zebra/Zebra 7.png',
      'Zebra 8': 'Skins/Zebra/Zebra 8.png',
      'Zebra 9': 'Skins/Zebra/Zebra 9.png',
    },
    Zombie: {
      '.DS_Store': 'Skins/Zombie/.DS_Store',
      'Zombie 1': 'Skins/Zombie/Zombie 1.png',
      'Zombie 2': 'Skins/Zombie/Zombie 2.png',
      'Zombie 3': 'Skins/Zombie/Zombie 3.png',
      'Zombie 4': 'Skins/Zombie/Zombie 4.png',
      'Zombie 5': 'Skins/Zombie/Zombie 5.png',
      'Zombie 6': 'Skins/Zombie/Zombie 6.png',
      'Zombie 7': 'Skins/Zombie/Zombie 7.png',
    },
  },
  Specialty: {
    Angel_Wings: {
      '1': 'Specialty/Angel_Wings/1.png',
      '2': 'Specialty/Angel_Wings/2.png',
      '3': 'Specialty/Angel_Wings/3.png',
      '4': 'Specialty/Angel_Wings/4.png',
      '5': 'Specialty/Angel_Wings/5.png',
      '6': 'Specialty/Angel_Wings/6.png',
      '7': 'Specialty/Angel_Wings/7.png',
      '8': 'Specialty/Angel_Wings/8.png',
    },
    Archer: {
      '1': 'Specialty/Archer/1.png',
      '2': 'Specialty/Archer/2.png',
      '3': 'Specialty/Archer/3.png',
    },
    Black_Eye: {
      '1': 'Specialty/Black_Eye/1.png',
      '2': 'Specialty/Black_Eye/2.png',
      '3': 'Specialty/Black_Eye/3.png',
      '4': 'Specialty/Black_Eye/4.png',
      '5': 'Specialty/Black_Eye/5.png',
      '6': 'Specialty/Black_Eye/6.png',
    },
    Devil_Wings: {
      '1': 'Specialty/Devil_Wings/1.png',
      '2': 'Specialty/Devil_Wings/2.png',
      '3': 'Specialty/Devil_Wings/3.png',
      '4': 'Specialty/Devil_Wings/4.png',
      '5': 'Specialty/Devil_Wings/5.png',
      '6': 'Specialty/Devil_Wings/6.png',
    },
    Earring: {
      '1': 'Specialty/Earring/1.png',
      '2': 'Specialty/Earring/2.png',
      '3': 'Specialty/Earring/3.png',
      '4': 'Specialty/Earring/4.png',
      '5': 'Specialty/Earring/5.png',
    },
    Forehead_Diamond: {
      '1': 'Specialty/Forehead_Diamond/1.png',
      '2': 'Specialty/Forehead_Diamond/2.png',
      '3': 'Specialty/Forehead_Diamond/3.png',
      '4': 'Specialty/Forehead_Diamond/4.png',
      '5': 'Specialty/Forehead_Diamond/5.png',
      '6': 'Specialty/Forehead_Diamond/6.png',
      '7': 'Specialty/Forehead_Diamond/7.png',
    },
    God_of_War: {
      '1': 'Specialty/God_of_War/1.png',
      '2': 'Specialty/God_of_War/2.png',
      '3': 'Specialty/God_of_War/3.png',
      '4': 'Specialty/God_of_War/4.png',
    },
    Mythic_Wings: {
      '1': 'Specialty/Mythic_Wings/1.png',
      '2': 'Specialty/Mythic_Wings/2.png',
      '3': 'Specialty/Mythic_Wings/3.png',
      '4': 'Specialty/Mythic_Wings/4.png',
      '5': 'Specialty/Mythic_Wings/5.png',
      '6': 'Specialty/Mythic_Wings/6.png',
      '7': 'Specialty/Mythic_Wings/7.png',
      '8': 'Specialty/Mythic_Wings/8.png',
    },
    Quarterback: {
      '1': 'Specialty/Quarterback/1.png',
      '2': 'Specialty/Quarterback/2.png',
      '3': 'Specialty/Quarterback/3.png',
      '4': 'Specialty/Quarterback/4.png',
    },
    Rockstar_Tats: {
      '1': 'Specialty/Rockstar_Tats/1.png',
      '2': 'Specialty/Rockstar_Tats/2.png',
      '3': 'Specialty/Rockstar_Tats/3.png',
      '4': 'Specialty/Rockstar_Tats/4.png',
    },
    Third_Eye: {
      '1': 'Specialty/Third_Eye/1.png',
      '2': 'Specialty/Third_Eye/2.png',
      '3': 'Specialty/Third_Eye/3.png',
      '4': 'Specialty/Third_Eye/4.png',
      '5': 'Specialty/Third_Eye/5.png',
      '6': 'Specialty/Third_Eye/6.png',
    },
  },
}

export const DEGODS_BASE_URL = {
  Backgrounds:
    'https://bafybeihnbn4zgm27jputfhxlbtlyain3k3kdfv6dnu37tb473zoowwdb6a.ipfs.dweb.link',
  Clothes:
    'https://bafybeigntq74czaglmytesw5u5bgqiuhghuzwxpyn2igijqy5vbzanpqbm.ipfs.dweb.link',
  Eyes: 'https://bafybeigim6kdmzlme4ai6hzfrhn3uymzuzsg4osjs5lfltifwhpqbew4im.ipfs.dweb.link/',
  Head: 'https://bafybeid3pam53yhwk67lku4kwizslyxkzqhyd5ddie4hwknlfmflvcdb34.ipfs.dweb.link',
  Mouth:
    'https://bafybeihnydqqpaeenlfvsntyy2y26ujpohrlmzqftksc5n7cqmdxysa2vi.ipfs.dweb.link',
  Neck: 'https://bafybeifa35pzmciwbxy6oqsk2rjjyojk2xzkbew5shbs5a3pnqugx6zxm4.ipfs.dweb.link',
  Skins:
    'https://bafybeihrzkh3bnp2n53xr77csfyj6uyyud7cie43oworzvs55343aavdpy.ipfs.dweb.link',
  Specialty:
    'https://bafybeib5zumzk2tzxn3pbixrp622xsqxvkpxlo5uvrjlrectpicsac2qvy.ipfs.dweb.link',
}

export const degodsTraitOrder = [
  'Backgrounds',
  'Specialty',
  'Skins',
  'Head',
  'Eyes',
  'Mouth',
  'Clothes',
  'Neck',
]
