export const languages = [
  { name: 'English', value: 'english', id: 1 },
  { name: 'Chinese', value: 'chinese', id: 2 },
  { name: 'Spanish', value: 'spanish', id: 3 },
  { name: 'Japanese', value: 'japanese', id: 4 },
  { name: 'Korean', value: 'korean', id: 5 },
  { name: 'German', value: 'german', id: 6 },
  { name: 'Russian', value: 'russian', id: 7 },
  { name: 'French', value: 'french', id: 8 },
  { name: 'Portuguese', value: 'portuguese', id: 9 },
  { name: 'Hindi', value: 'hindi', id: 10 },
  { name: 'Arabic', value: 'arabic', id: 11 },
  { name: 'Turkish', value: 'turkish', id: 12 },
  { name: 'Dutch', value: 'dutch', id: 13 },
  { name: 'Indonesian', value: 'indonesian', id: 14 },
  { name: 'Italian', value: 'italian', id: 15 },
]

export const locations = [
  { name: 'United States', value: 'us', id: 1 },
  { name: 'United Kingdom', value: 'uk', id: 2 },
  { name: 'Canada', value: 'ca', id: 3 },
  { name: 'Singapore', value: 'sg', id: 4 },
  { name: 'South Korea', value: 'kr', id: 5 },
  { name: 'Germany', value: 'de', id: 6 },
  { name: 'Australia', value: 'au', id: 7 },
  { name: 'Japan', value: 'jp', id: 8 },
  { name: 'China', value: 'cn', id: 9 },
  { name: 'India', value: 'in', id: 10 },
  { name: 'Netherlands', value: 'nl', id: 11 },
  { name: 'France', value: 'fr', id: 12 },
  { name: 'United Arab Emirates', value: 'ae', id: 13 },
  { name: 'Switzerland', value: 'ch', id: 14 },
  { name: 'Russia', value: 'ru', id: 15 },
  { name: 'Spain', value: 'es', id: 16 },
  { name: 'Italy', value: 'it', id: 17 },
  { name: 'Brazil', value: 'br', id: 18 },
  { name: 'Sweden', value: 'se', id: 19 },
  { name: 'Mexico', value: 'mx', id: 20 },
  { name: 'South Africa', value: 'za', id: 21 },
  { name: 'Turkey', value: 'tr', id: 22 },
  { name: 'Israel', value: 'il', id: 23 },
  { name: 'Hong Kong', value: 'hk', id: 24 },
  { name: 'New Zealand', value: 'nz', id: 25 },
  { name: 'Belgium', value: 'be', id: 26 },
  { name: 'Ireland', value: 'ie', id: 27 },
  { name: 'Austria', value: 'at', id: 28 },
  { name: 'Indonesia', value: 'id', id: 29 },
  { name: 'Philippines', value: 'ph', id: 30 },
  { name: 'Vietnam', value: 'vn', id: 31 },
  { name: 'Thailand', value: 'th', id: 32 },
  { name: 'Malaysia', value: 'my', id: 33 },
  { name: 'Saudi Arabia', value: 'sa', id: 34 },
  { name: 'Norway', value: 'no', id: 35 },
  { name: 'Denmark', value: 'dk', id: 36 },
  { name: 'Finland', value: 'fi', id: 37 },
  { name: 'Poland', value: 'pl', id: 38 },
  { name: 'Ukraine', value: 'ua', id: 39 },
  { name: 'Czech Republic', value: 'cz', id: 40 },
  { name: 'Romania', value: 'ro', id: 41 },
  { name: 'Argentina', value: 'ar', id: 42 },
  { name: 'Nigeria', value: 'ng', id: 43 },
  { name: 'Egypt', value: 'eg', id: 44 },
  { name: 'Kenya', value: 'ke', id: 45 },
  { name: 'Morocco', value: 'ma', id: 46 },
  { name: 'Pakistan', value: 'pk', id: 47 },
  { name: 'Bangladesh', value: 'bd', id: 48 },
  { name: 'Iraq', value: 'iq', id: 49 },
  { name: 'Iran', value: 'ir', id: 50 },
  { name: 'Lebanon', value: 'lb', id: 51 },
  { name: 'Jordan', value: 'jo', id: 52 },
  { name: 'Portugal', value: 'pt', id: 53 },
  { name: 'Greece', value: 'gr', id: 54 },
  { name: 'Hungary', value: 'hu', id: 55 },
  { name: 'Slovakia', value: 'sk', id: 56 },
  { name: 'Bulgaria', value: 'bg', id: 57 },
  { name: 'Croatia', value: 'hr', id: 58 },
  { name: 'Serbia', value: 'rs', id: 59 },
  { name: 'Bosnia and Herzegovina', value: 'ba', id: 60 },
  { name: 'Montenegro', value: 'me', id: 61 },
  { name: 'Albania', value: 'al', id: 62 },
  { name: 'Kosovo', value: 'xk', id: 63 },
  { name: 'North Macedonia', value: 'mk', id: 64 },
  { name: 'Slovenia', value: 'si', id: 65 },
  { name: 'Luxembourg', value: 'lu', id: 66 },
  { name: 'Belarus', value: 'by', id: 67 },
  { name: 'Afghanistan', value: 'af', id: 68 },
  { name: 'Syria', value: 'sy', id: 69 },
]
