export const YOOTSMAPPER = {
  Background: {
    'Redlines 11 3': 'Background/Redlines 11 3.png',
    'Untitled_Artwork-1 17': 'Background/Untitled_Artwork-1 17.png',
    'Untitled_Artwork-2 18': 'Background/Untitled_Artwork-2 18.png',
    'Untitled_Artwork-4 10': 'Background/Untitled_Artwork-4 10.png',
    'Untitled_Artwork-5 5': 'Background/Untitled_Artwork-5 5.png',
    'blue_skies#1': 'Background/blue_skies%231.png',
    'downtown#1': 'Background/downtown%231.png',
    'forrest#1': 'Background/forrest%231.png',
    purple: 'Background/purple.png',
    red: 'Background/red.png',
    'sand_dollar 7 1': 'Background/sand_dollar 7 1.png',
    'space_planet#1': 'Background/space_planet%231.png',
  },
  Clothes: {
    IMG_4218: 'Clothes/IMG_4218.png',
    IMG_4249: 'Clothes/IMG_4249.png',
    IMG_4252: 'Clothes/IMG_4252.png',
    'IMG_4270 1': 'Clothes/IMG_4270 1.png',
    'IMG_4272 1': 'Clothes/IMG_4272 1.png',
    'IMG_4311 1': 'Clothes/IMG_4311 1.png',
    'IMG_4505 1': 'Clothes/IMG_4505 1.png',
    'Untitled-Artwork (15) 1': 'Clothes/Untitled-Artwork (15) 1.png',
    'Untitled-Artwork (3) 1': 'Clothes/Untitled-Artwork (3) 1.png',
    'Untitled-Artwork (4) 1': 'Clothes/Untitled-Artwork (4) 1.png',
    'Untitled_Artwork 231 3': 'Clothes/Untitled_Artwork 231 3.png',
    'Untitled_Artwork 232 3': 'Clothes/Untitled_Artwork 232 3.png',
    'Untitled_Artwork 233 3': 'Clothes/Untitled_Artwork 233 3.png',
    'Untitled_Artwork 680 4': 'Clothes/Untitled_Artwork 680 4.png',
    'Untitled_Artwork 681 3': 'Clothes/Untitled_Artwork 681 3.png',
    'Untitled_Artwork 685 2': 'Clothes/Untitled_Artwork 685 2.png',
    'Untitled_Artwork 800': 'Clothes/Untitled_Artwork 800.png',
    'Untitled_Artwork-11': 'Clothes/Untitled_Artwork-11.png',
    'Untitled_Artwork-13': 'Clothes/Untitled_Artwork-13.png',
    'anon#1': 'Clothes/anon%231.png',
    'army_vest#0': 'Clothes/army_vest%230.png',
    asfasfasgf: 'Clothes/asfasfasgf.png',
    'astronaut_suit#0': 'Clothes/astronaut_suit%230.png',
    'barista_apron#0': 'Clothes/barista_apron%230.png',
    'baseball_jersey#1': 'Clothes/baseball_jersey%231.png',
    'basketball_jersey#2': 'Clothes/basketball_jersey%232.png',
    'biker_vest#1': 'Clothes/biker_vest%231.png',
    'bitcoin_cutoff 2': 'Clothes/bitcoin_cutoff 2.png',
    'black_hoodie#2': 'Clothes/black_hoodie%232.png',
    'black_y00tah_jersey#2': 'Clothes/black_y00tah_jersey%232.png',
    'bomber#3': 'Clothes/bomber%233.png',
    'bored_blue (1)': 'Clothes/bored_blue (1).png',
    'bored_blue (2)': 'Clothes/bored_blue (2).png',
    'bored_blue (3)': 'Clothes/bored_blue (3).png',
    'bored_blue (4)': 'Clothes/bored_blue (4).png',
    'bored_blue (5)': 'Clothes/bored_blue (5).png',
    'bored_blue (6)': 'Clothes/bored_blue (6).png',
    'bored_blue (9)': 'Clothes/bored_blue (9).png',
    'bored_blue 1': 'Clothes/bored_blue 1.png',
    bored_blue: 'Clothes/bored_blue.png',
    'bowling_shirt_green#1': 'Clothes/bowling_shirt_green%231.png',
    'boxing_robe#1': 'Clothes/boxing_robe%231.png',
    'bulletproof_vest_cream#1': 'Clothes/bulletproof_vest_cream%231.png',
    'cactus_jack 3': 'Clothes/cactus_jack 3.png',
    'college_crewneck_green#1': 'Clothes/college_crewneck_green%231.png',
    'construction_vest#1': 'Clothes/construction_vest%231.png',
    'cream_cut_off#1': 'Clothes/cream_cut_off%231.png',
    'cream_hoodie#1': 'Clothes/cream_hoodie%231.png',
    cutoff: 'Clothes/cutoff.png',
    'denim_jacket_black#1': 'Clothes/denim_jacket_black%231.png',
    'denim_jacket_blue#1': 'Clothes/denim_jacket_blue%231.png',
    'denim_overalls#1': 'Clothes/denim_overalls%231.png',
    denim_patches: 'Clothes/denim_patches.png',
    'detective_coat#1': 'Clothes/detective_coat%231.png',
    'football_jersey_green#1': 'Clothes/football_jersey_green%231.png',
    'gold_tux#1': 'Clothes/gold_tux%231.png',
    'hawaiian_blue#1': 'Clothes/hawaiian_blue%231.png',
    'hazmat#1': 'Clothes/hazmat%231.png',
    'hockey_jersey#1': 'Clothes/hockey_jersey%231.png',
    'kimono#1': 'Clothes/kimono%231.png',
    'letterman_jacket#1': 'Clothes/letterman_jacket%231.png',
    'mechanic#1': 'Clothes/mechanic%231.png',
    'mickey_shirt#1': 'Clothes/mickey_shirt%231.png',
    'newhawaiian#7': 'Clothes/newhawaiian%237.png',
    'olive_tee#1': 'Clothes/olive_tee%231.png',
    'orange_puffer#1': 'Clothes/orange_puffer%231.png',
    'pajamas_blue#1': 'Clothes/pajamas_blue%231.png',
    party_shirt: 'Clothes/party_shirt.png',
    'pink_polo_sweater#1': 'Clothes/pink_polo_sweater%231.png',
    'polo_chain#0': 'Clothes/polo_chain%230.png',
    'professor#0': 'Clothes/professor%230.png',
    'racer_jacket#0': 'Clothes/racer_jacket%230.png',
    'racing_suit 4': 'Clothes/racing_suit 4.png',
    'red_pajamas#0': 'Clothes/red_pajamas%230.png',
    shirtless_overalls: 'Clothes/shirtless_overalls.png',
    'ski_jacket#0': 'Clothes/ski_jacket%230.png',
    'stock_broker_suspenders#0': 'Clothes/stock_broker_suspenders%230.png',
    sweater_pink: 'Clothes/sweater_pink.png',
    tatata: 'Clothes/tatata.png',
    'turtleneck_chain#0': 'Clothes/turtleneck_chain%230.png',
    'vallet_jacket#0': 'Clothes/vallet_jacket%230.png',
    'white_polo#0': 'Clothes/white_polo%230.png',
    'white_tank#1': 'Clothes/white_tank%231.png',
    'y00t_vest#1': 'Clothes/y00t_vest%231.png',
    'y00tah_jersey_red#1': 'Clothes/y00tah_jersey_red%231.png',
    'yellow_puffer#1': 'Clothes/yellow_puffer%231.png',
    yootstock: 'Clothes/yootstock.png',
  },
  Eyes: {
    IMG_4253: 'Eyes/IMG_4253.png',
    IMG_4254: 'Eyes/IMG_4254.png',
    IMG_4255: 'Eyes/IMG_4255.png',
    IMG_4257: 'Eyes/IMG_4257.png',
    IMG_4739: 'Eyes/IMG_4739.png',
    IMG_4786: 'Eyes/IMG_4786.png',
    'Redlines 298 1': 'Eyes/Redlines 298 1.png',
    'Redlines 71 5': 'Eyes/Redlines 71 5.png',
    'Redlines 77 2': 'Eyes/Redlines 77 2.png',
    'Redlines 78 5': 'Eyes/Redlines 78 5.png',
    'Redlines 85 2': 'Eyes/Redlines 85 2.png',
    'Untitled_Artwork 751 2': 'Eyes/Untitled_Artwork 751 2.png',
    'Untitled_Artwork 754 2': 'Eyes/Untitled_Artwork 754 2.png',
    'Untitled_Artwork 758 1': 'Eyes/Untitled_Artwork 758 1.png',
    'Untitled_Artwork 776 1': 'Eyes/Untitled_Artwork 776 1.png',
    'Untitled_Artwork 779 1': 'Eyes/Untitled_Artwork 779 1.png',
    'Untitled_Artwork 794 1': 'Eyes/Untitled_Artwork 794 1.png',
    'all_seeing_eyes#3': 'Eyes/all_seeing_eyes%233.png',
    'big_black_shades#4': 'Eyes/big_black_shades%234.png',
    'big_reading 4': 'Eyes/big_reading 4.png',
    'black_rim_shades#3': 'Eyes/black_rim_shades%233.png',
    'bored_blue (1)_1': 'Eyes/bored_blue (1)_1.png',
    'bored_blue (2) 2': 'Eyes/bored_blue (2) 2.png',
    'bored_blue (2)_1': 'Eyes/bored_blue (2)_1.png',
    bored_blue_1: 'Eyes/bored_blue_1.png',
    'cartoon_sunnies#3': 'Eyes/cartoon_sunnies%233.png',
    'cat_eye_shades#2': 'Eyes/cat_eye_shades%232.png',
    'classic_readers#4': 'Eyes/classic_readers%234.png',
    'dsda 2': 'Eyes/dsda 2.png',
    'funky_shades#3': 'Eyes/funky_shades%233.png',
    glasses_1: 'Eyes/glasses_1.png',
    'goggle_face 4': 'Eyes/goggle_face 4.png',
    'gold_readers#1': 'Eyes/gold_readers%231.png',
    'hypnotized_eyes#1': 'Eyes/hypnotized_eyes%231.png',
    'pencil#2': 'Eyes/pencil%232.png',
    'pencilz_red 4': 'Eyes/pencilz_red 4.png',
    'rockstar_paint#1': 'Eyes/rockstar_paint%231.png',
    'round_af 4': 'Eyes/round_af 4.png',
    'scarface_glasses#4': 'Eyes/scarface_glasses%234.png',
    'snake_eyess 2': 'Eyes/snake_eyess 2.png',
    'viper_glasses#2': 'Eyes/viper_glasses%232.png',
    'why_is_everything_chrome 1': 'Eyes/why_is_everything_chrome 1.png',
    'y00t_goggles#2': 'Eyes/y00t_goggles%232.png',
  },
  Head: {
    '371780AD-684E-4473-B9A1-3E5A1985280E 1':
      'Head/371780AD-684E-4473-B9A1-3E5A1985280E 1.png',
    '3_1sagsagasgasg': 'Head/3_1sagsagasgasg.png',
    Beanie_z: 'Head/Beanie_z.png',
    'IMG_4312 1': 'Head/IMG_4312 1.png',
    IMG_4359: 'Head/IMG_4359.png',
    IMG_4362: 'Head/IMG_4362.png',
    IMG_4428: 'Head/IMG_4428.png',
    IMG_4430: 'Head/IMG_4430.png',
    'IMG_4432 1': 'Head/IMG_4432 1.png',
    IMG_4569: 'Head/IMG_4569.png',
    IMG_4570: 'Head/IMG_4570.png',
    IMG_4574: 'Head/IMG_4574.png',
    IMG_4576: 'Head/IMG_4576.png',
    IMG_4578: 'Head/IMG_4578.png',
    IMG_4618: 'Head/IMG_4618.png',
    IMG_4620: 'Head/IMG_4620.png',
    IMG_4622: 'Head/IMG_4622.png',
    IMG_4624: 'Head/IMG_4624.png',
    IMG_4626: 'Head/IMG_4626.png',
    IMG_4628: 'Head/IMG_4628.png',
    IMG_4630: 'Head/IMG_4630.png',
    IMG_4632: 'Head/IMG_4632.png',
    IMG_4634: 'Head/IMG_4634.png',
    IMG_4636: 'Head/IMG_4636.png',
    IMG_4638: 'Head/IMG_4638.png',
    IMG_4686: 'Head/IMG_4686.png',
    IMG_4688: 'Head/IMG_4688.png',
    IMG_4690: 'Head/IMG_4690.png',
    IMG_4702: 'Head/IMG_4702.png',
    IMG_4704: 'Head/IMG_4704.png',
    IMG_4706: 'Head/IMG_4706.png',
    'IMG_4717 1': 'Head/IMG_4717 1.png',
    IMG_4725: 'Head/IMG_4725.png',
    IMG_4747: 'Head/IMG_4747.png',
    IMG_4751: 'Head/IMG_4751.png',
    'Redlines 163 1': 'Head/Redlines 163 1.png',
    'Redlines 182 1': 'Head/Redlines 182 1.png',
    'Redlines 299 1': 'Head/Redlines 299 1.png',
    'Redlines 84 2': 'Head/Redlines 84 2.png',
    'Redlines 99': 'Head/Redlines 99.png',
    'Untitled-Artwork (16)': 'Head/Untitled-Artwork (16).png',
    'Untitled-Artwork (18) 1': 'Head/Untitled-Artwork (18) 1.png',
    'Untitled-Artwork (2) 1': 'Head/Untitled-Artwork (2) 1.png',
    'Untitled-Artwork (7) 1': 'Head/Untitled-Artwork (7) 1.png',
    'Untitled-Artwork (8) 1': 'Head/Untitled-Artwork (8) 1.png',
    'Untitled_Artwork 250 1': 'Head/Untitled_Artwork 250 1.png',
    'Untitled_Artwork 675 4': 'Head/Untitled_Artwork 675 4.png',
    'Untitled_Artwork 760 1': 'Head/Untitled_Artwork 760 1.png',
    'Untitled_Artwork 788 1': 'Head/Untitled_Artwork 788 1.png',
    'Untitled_Artwork 827': 'Head/Untitled_Artwork 827.png',
    'Untitled_Artwork-10 2': 'Head/Untitled_Artwork-10 2.png',
    'Untitled_Artwork-7 2': 'Head/Untitled_Artwork-7 2.png',
    'Untitled_Artwork-8 2': 'Head/Untitled_Artwork-8 2.png',
    'Untitled_Artwork-9 2': 'Head/Untitled_Artwork-9 2.png',
    Yoots_alien_2: 'Head/Yoots_alien_2.png',
    'airpods#2': 'Head/airpods%232.png',
    bandana_black: 'Head/bandana_black.png',
    'biker_bandana#3': 'Head/biker_bandana%233.png',
    'black_hatt 4': 'Head/black_hatt 4.png',
    'bleached_hair#4': 'Head/bleached_hair%234.png',
    'bored_blue (14)': 'Head/bored_blue (14).png',
    'bored_blue (3)_1': 'Head/bored_blue (3)_1.png',
    'bored_blue (4)_1': 'Head/bored_blue (4)_1.png',
    'construction_helmet#1': 'Head/construction_helmet%231.png',
    'cowboy_hat#1': 'Head/cowboy_hat%231.png',
    cream_uphat: 'Head/cream_uphat.png',
    'd00lan_helmet 1': 'Head/d00lan_helmet 1.png',
    'd00lan_helmet_black#1': 'Head/d00lan_helmet_black%231.png',
    feather_hat: 'Head/feather_hat.png',
    'fisherman_hat#3': 'Head/fisherman_hat%233.png',
    'five_panel_hat#2': 'Head/five_panel_hat%232.png',
    'flower#1': 'Head/flower%231.png',
    'forehead_shades#0': 'Head/forehead_shades%230.png',
    'fur_hawk#1': 'Head/fur_hawk%231.png',
    'gamer_headset#0': 'Head/gamer_headset%230.png',
    'general_beret 2': 'Head/general_beret 2.png',
    gold_laurel: 'Head/gold_laurel.png',
    'halo#0': 'Head/halo%230.png',
    'head_goggles#2': 'Head/head_goggles%232.png',
    'icecream_crown#0': 'Head/icecream_crown%230.png',
    'military_helmet#2': 'Head/military_helmet%232.png',
    'mullet#1': 'Head/mullet%231.png',
    'preppy_visor#3': 'Head/preppy_visor%233.png',
    'shoey_guzzler#1': 'Head/shoey_guzzler%231.png',
    'skate_helmet_yellow 1': 'Head/skate_helmet_yellow 1.png',
    'skate_pro 4': 'Head/skate_pro 4.png',
    'skater_beanie_orange#0': 'Head/skater_beanie_orange%230.png',
    'spiked_hair#1': 'Head/spiked_hair%231.png',
    'tie_around_head#2': 'Head/tie_around_head%232.png',
    'top_hat#1': 'Head/top_hat%231.png',
    'viper_glasses#2': 'Head/viper_glasses%232.png',
    wizard_1_z: 'Head/wizard_1_z.png',
    wizard_3_z: 'Head/wizard_3_z.png',
  },
  Skins: {
    'Redlines 127 1': 'Skins/Redlines 127 1.png',
    'Redlines 144 1': 'Skins/Redlines 144 1.png',
    'Redlines 165 2': 'Skins/Redlines 165 2.png',
    'Redlines 283 1': 'Skins/Redlines 283 1.png',
    'Redlines 4 15': 'Skins/Redlines 4 15.png',
    'Redlines 5 10': 'Skins/Redlines 5 10.png',
    'Redlines 7 11': 'Skins/Redlines 7 11.png',
    'Untitled-Artwork (26)': 'Skins/Untitled-Artwork (26).png',
    'Untitled-Artwork (27)': 'Skins/Untitled-Artwork (27).png',
    'Untitled-Artwork (54)': 'Skins/Untitled-Artwork (54).png',
    'Untitled-Artwork (55)_1': 'Skins/Untitled-Artwork (55)_1.png',
    'Untitled-Artwork (57)_1': 'Skins/Untitled-Artwork (57)_1.png',
    'Untitled_Artwork 183 6': 'Skins/Untitled_Artwork 183 6.png',
    'Untitled_Artwork 184 3': 'Skins/Untitled_Artwork 184 3.png',
    'Untitled_Artwork 234 4': 'Skins/Untitled_Artwork 234 4.png',
    'black_bored#1': 'Skins/black_bored%231.png',
    'blended_ice 1': 'Skins/blended_ice 1.png',
    'blue_duh#0': 'Skins/blue_duh%230.png',
    'brown_duh_eyes#1': 'Skins/brown_duh_eyes%231.png',
    'cement_bored_eyes#3_1': 'Skins/cement_bored_eyes%233_1.png',
    'chrome_bored#1': 'Skins/chrome_bored%231.png',
    'chrome_bored#6': 'Skins/chrome_bored%236.png',
    cloud_fur_sheesh: 'Skins/cloud_fur_sheesh.png',
    'diamond_bored#0': 'Skins/diamond_bored%230.png',
    digital_sheesh: 'Skins/digital_sheesh.png',
    'galaxy mockup 1': 'Skins/galaxy mockup 1.png',
    galaxy: 'Skins/galaxy.png',
    gummy2: 'Skins/gummy2.png',
    'highlighter_happy#0': 'Skins/highlighter_happy%230.png',
    'ice_cream_bored_eyebrows#0': 'Skins/ice_cream_bored_eyebrows%230.png',
    'pink_bored_eyes#0': 'Skins/pink_bored_eyes%230.png',
    'rock_bored#0': 'Skins/rock_bored%230.png',
    'skeleton_fur#0': 'Skins/skeleton_fur%230.png',
    'slime_skin#0': 'Skins/slime_skin%230.png',
    'smiley_fur#0': 'Skins/smiley_fur%230.png',
    'star_skin_happy#1': 'Skins/star_skin_happy%231.png',
    'starry_blue#0': 'Skins/starry_blue%230.png',
    'teal_bored_eyes#0': 'Skins/teal_bored_eyes%230.png',
    'textured_brown_happy#1': 'Skins/textured_brown_happy%231.png',
    'tiger_duh_eyes#0': 'Skins/tiger_duh_eyes%230.png',
    yellow_smiler: 'Skins/yellow_smiler.png',
    'zebra_bored_eyes#1': 'Skins/zebra_bored_eyes%231.png',
    'zombie_sheesh#0': 'Skins/zombie_sheesh%230.png',
  },
}
export const YOOTS_BASE_URL =
  'https://bafybeidz4pvfdd6yyu4mx3xwfo2imxfjtwc3vugmcrgfeq5u7skgj36moy.ipfs.dweb.link'
// export const YOOTS_BASE_URL = 'https://bafybeihu3veecxn5bscv3jrenittgviqkbe4epek6poggozbbdsx2vm6jy.ipfs.dweb.link'

export const yootsTraitOrder = [
  'Background',
  'Skins',
  'Clothes',
  'Eyes',
  'Head',
]
