import "./globals.css";

import type { Metadata } from "next";
import { Inter, Luckiest_Guy } from "next/font/google";
import { Providers } from "./Providers.client";
import { Rowdies } from "next/font/google";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

const lucky = Luckiest_Guy({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-lucky",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const rowdies = Rowdies({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  variable: "--font-rowdies",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`dark ${rowdies.variable} ${lucky.variable}`}>
      <Providers>
        <body className={inter.className}>
          {/* <Navbar /> */}
          {children}
        </body>
      </Providers>
    </html>
  );
}
